### ISSUE TITLE
Make it app by default in Gnome

### ISSUE THREAD

**Issue by gnacho** [brrd/Abricotine#100]
I'm using Gnome 3.22 under Arch (Apricity OS), and Abricotine is not shown in the list of programs to open by default .md files, so I can't use it by default. Any idea how to fix this?

**Comment by brrd** [comment]
This is related to #8. 

Currently Abricotine is just a portable app, so it doesn't affect your OS (shortcuts in startup menu, file associations...). This is why packages/installers are planned (quite soon, I hope ).
