### ISSUE TITLE
Removing format leaves trailing symbols

### ISSUE THREAD

**Issue by darahak** [brrd/Abricotine#102]
When we want to remove formatting using shortcuts from the `Format` menu, it leaves trailing symbols if the selection is followed by another character (most of the time, it's punctuation).

An example with bold:
```
- Before:
**Note**: Beware

- After:
Note**: Beware

- Second time:
**Note****: Beware
Note****: Beware
```

**Comment by brrd** [comment]
Fixed on develop (#106).
