### ISSUE TITLE
⌘Q in OS X is used to Quote, but it should instead Quit the app

### ISSUE THREAD

**Issue by casidiablo** [brrd/Abricotine#11]
Actually, the main menu in the tool bar says that you have to press ⌘Q to quit the app, which is a common convention all across OS X. Abricotine overwrites this shortcut and use it instead to insert quotes.

**Comment by AgentEpsilon** [comment]
Just created PR #21, which fixes this problem.

**Comment by brrd** [comment]
Fixed in #25 thanks to @AgentEpsilon !
It has been merged in develop branch, so this will become effective in next release.
