### ISSUE TITLE
Cursor doesn't show up on initial launch

### ISSUE THREAD

**Issue by nloveladyallen** [brrd/Abricotine#110]
The blinking cursor only shows up after typing the first character of a document.

**Comment by brrd** [comment]
Which platform? Which version? Which way to install (installer, archive or manual building)?

**Comment by nloveladyallen** [comment]
macOS, 0.4.0, built from master.

**Comment by jgclark** [comment]
Ditto. macOS latest, 0.4.0 from cask install.

**Comment by brrd** [comment]
Probably related to https://discuss.codemirror.net/t/codemirror-cursor-is-not-partially-visible/648
