### ISSUE TITLE
Default option and text for “Close without saving”

### ISSUE THREAD

**Issue by nloveladyallen** [brrd/Abricotine#112]
![screen shot 2016-10-26 at 8 04 00 pm](https://cloud.githubusercontent.com/assets/10617484/19749488/62cff268-9bb7-11e6-9858-de9171d8a2f7.png)

<img width="807" alt="screen shot 2016-10-26 at 8 11 47 pm" src="https://cloud.githubusercontent.com/assets/10617484/19749627/7906c4de-9bb8-11e6-93cc-3d640a5791f8.png">

<img width="1097" alt="screen shot 2016-10-26 at 8 06 01 pm" src="https://cloud.githubusercontent.com/assets/10617484/19749531/aced1b6e-9bb7-11e6-835b-9b98bfab3eba.png">

The default option should be to save the document, and the options should be title cased. I would also consider changing the text to “Don’t Save”/“Cancel”/“Save…”.

**Comment by darahak** [comment]
Does it happen only on MacOS? On Windows 7, it defaults to "Save and close".

**Comment by nloveladyallen** [comment]
@darahak Really? That’s interesting.

**Comment by darahak** [comment]
The documentation for [dialog.showMessageBox](http://electron.atom.io/docs/api/dialog/#dialogshowmessageboxbrowserwindow-options-callback) shows a `defaultId` option to choose which button should be selected by default.

But it's not clear how the behavior may change depending on the OS.
