### ISSUE TITLE
Use local copy of MathJax/highlight.js in HTML export instead of loading of CDN

### ISSUE THREAD

**Issue by nloveladyallen** [brrd/Abricotine#115]
No reason to depend on the network for HTML export.

**Comment by brrd** [comment]
Yes there is a good reason: MathJax is about 60 Mo, which is definitely too heavy for a single text document. If you really want to have it into you export you can edit your template and clone the lib into its assets directory. See https://github.com/brrd/Abricotine/blob/master/docs/templates.md
