### ISSUE TITLE
rtl context-menu !?

### ISSUE THREAD

**Issue by Tavousi** [brrd/Abricotine#118]
Hi,
there is any way to show context menu from right to left ?! for persian language ?

**Comment by brrd** [comment]
Translations are planned (#59) but not totally implemented. Right now context menu is in English only, so I don't really understand your request.

**Comment by Hitaro** [comment]
This question is a feature request: the ability to move the sidebar from lift side of application to right. In right-to-left languages such as Arabic and also Persian, it's more comfortable for users to have options in right side.

**Comment by brrd** [comment]
@Hitaro This is another issue: #159.

By the way, I'm closing this feature request until we get more details about it.
