### ISSUE TITLE
Is there a way to support you?

### ISSUE THREAD

**Issue by szelpe** [brrd/Abricotine#119]
Hi!

You created a really awesome editor, with the latest release I can do basically everything I wanted but wasn't able with the previous versions.

Is there a way to help you out, e.g. by donating or something else?

**Comment by brrd** [comment]
Thank you very much for your message!

There are many ways to contribute to the project: pulling code of course, but also posting bug reports or answers whenever you can... You can also talk about the project around you, I think it's a good way to find new contributors and thus to stimulate development 😉

I'm making this app on my free time for my pleasure and for learning programming. I personally don't rely on donations but some other developers who indirectly contributed to this project do. I'm thinking at @marijnh who wrote [CodeMirror](https://github.com/codemirror/CodeMirror), a great javascript library without which Abricotine would not exist. But [he is not the only one](https://github.com/brrd/Abricotine/blob/master/package.json#L33) of course. In my opinion, donating to such projects is another good way to contribute to Abricotine development.
