### ISSUE TITLE
Distribution on OS X (release page, brew cask, etc.)

### ISSUE THREAD

**Issue by casidiablo** [brrd/Abricotine#12]
So I liked this project so much that I'd love to help maintain a [cask](https://github.com/caskroom/homebrew-cask), so OS X users just have to run `brew cask install abricotine`. I went ahead and opened a PR on `hombrew-cask`: [#19095](https://github.com/caskroom/homebrew-cask/pull/19095). The version I built was based on the current master branch (i.e. 9efa2c6)

Is there a reason why you haven't done this before? If it's just lack of time/resources I volunteer to maintain this.

homebrew-cask guys say they can accept this cask as official if the URL used is referenced either in this repo or in the website. For obvious reasons, they don't like the idea of a third party developer building and hosting the app.

**Comment by sdaitzman** [comment]
:+1:

**Comment by brrd** [comment]
Hi,

> Is there a reason why you haven't done this before? 

At the very beginning OSX support wasn't planned at all. I'm a Linux user and I can borrow a PC with Windows when I need to package the app for Win, but I have no easy way to get OSX. Plus I don't really know about OSX platform. Two weeks ago a contributor [submitted a PR](https://github.com/brrd/Abricotine/pull/2) which added the OSX support to Abricotine. That's how it happened and I think it is a very good thing, but I still do not have the means to provide support for it.

This project is wide open to contributions, so if you want to maintain an OSX version you are welcome. I would mention you as the maintainer of this build, so everything would be clear for users.

Just a question: I don't know Cask. I understand it is a package manager for OSX, is it? What's the difference with a traditional packaged app?

**Comment by sdaitzman** [comment]
On OS X, most apps are distributed one of two ways. They either come in a disk image with a symlink to your Applications folder, and you drag them to that symlink to install them, or they come in a .pkg or .mpkg installer which handles installation for you. Homebrew is a more traditional linux-y package manager that allows you to `$ brew install node` etc. and brew cask is an addition that lets you use Homebrew to install GUI apps.

**Comment by casidiablo** [comment]
Cool. I propose you upload the [OS X zip](https://s3.amazonaws.com/abricotine/Abricotine.zip) to the releases page on Github. That way I can just reference that one on the cask PR and they won't complain about it.

Also, do you want to tag the current master's HEAD and create a new release or should I rebuild the zip out of https://github.com/brrd/Abricotine/releases/tag/0.2.2?

**Comment by brrd** [comment]
Done: https://github.com/brrd/Abricotine/releases/tag/0.2.2

> Also, do you want to tag the current master's HEAD and create a new release or should I rebuild the zip out of https://github.com/brrd/Abricotine/releases/tag/0.2.2? 

No, I think it's okay. Nothing changed except README.md since 9efa2c6
Thanks @casidiablo !

**Comment by adidalal** [comment]
Officially merged in https://github.com/caskroom/homebrew-cask/commit/d3d6d573edaa8e2fd59ffda1bcd134211000349c (Used 0.2.2 tag as that was the last release)

`brew cask install abricotine` is now available. (Feel free to add it to your readme, as a method of installation on OS X).

**Comment by brrd** [comment]
Obviously it is not working here: #29

**Comment by adidalal** [comment]
Commented on the post, feel free to redirect users to our issues section for issues like that (it was just caused by an outdated cask install)
