### ISSUE TITLE
Change default paths for Save and Export

### ISSUE THREAD

**Issue by darahak** [brrd/Abricotine#129]
When I want to save a document or export it to HTML, the app shows me the app directory, which I would never use for document storage.

It does this on Windows, I don't know about the other platforms.

IMHO it should propose to save in the **user profile directory** or its `Documents` directory if it exists.
And for export, the **same location** as the document if it was saved. If not, fall back on the previous proposition.

It bothers me especially when I do multiple exports and have to select the right path every time.

Also, the **save dialog** should remember the previous location that the user chose.
I don't know if it's possible though, I should check the documentation.

**Comment by brrd** [comment]
An idea: we could use the recent docs (see #92) to store and retrieve this path.

**Comment by nloveladyallen** [comment]
Really? I get the root directory on macOS (which I also would never use for document storage). 

For remembering the last directory, see #92.

**Comment by darahak** [comment]
FWIW, I think changing the current directory on save would be cheaper and easier to maintain.
I didn't know about `app.getPath()`, this is really cool.
