### ISSUE TITLE
electron-prebuilt deprecated

### ISSUE THREAD

**Issue by jmhibben** [brrd/Abricotine#130]
While building Abricotine from source, npm issued the following warning:

`npm WARN deprecated electron-prebuilt@1.3.9: electron-prebuilt has been renamed to electron. For more details, see http://electron.atom.io/blog/2016/08/16/npm-install-electron`

This should be corrected in `package.json` before the `electron-prebuilt` package is too far outdated or removed.

**Comment by darahak** [comment]
Note: `electron-prebuilt` will stop being updated after the end of this year.
