### ISSUE TITLE
[Dev] ES2015?

### ISSUE THREAD

**Issue by darahak** [brrd/Abricotine#140]
Just wondering, is it okay if contributors start pushing ES2015 code?

Sometimes I really want to use stuff like [template strings](https://developers.google.com/web/updates/2015/01/ES6-Template-Strings) or [arrow functions](http://exploringjs.com/es6/ch_arrow-functions.html) (mainly to ditch the `var that = this` trick), but I don't know if I should.

**Comment by brrd** [comment]
I totally agree that ES2015 syntax is more comfortable but until now I was afraid that mixing it with the old syntax would make everything confusing 😕 Moreover it is not fully compatible with node 4 (which is still widely used). 

In my opinion we should keep the code consistent even if it's not really convenient. If you don't like `var that = this` you can use `fn.bind(this)` which is maybe prettier.

**Comment by darahak** [comment]
I understand your concerns, no problem :+1: 
I have doubts about the impact of older versions of Node though.

I might be wrong, but since Electron has its own Node runtime, it should not be affected by a user's Node install, right?

Looking at the [releases](https://github.com/electron/electron/releases?after=v1.2.3) page for Electron, it looks like it's using Chromium 51 and Node 6.1.0, which have respectively 97% and 92% ES2015 support ([compatibility table](http://kangax.github.io/compat-table/es6)).

**Comment by brrd** [comment]
> I might be wrong, but since Electron has its own Node runtime, it should not be affected by a user's Node install, right?

Yes, you are right of course. My mistake.

Lets say I would merge contributions using ES 2015 if the code is clear and consistent. Personally I prefer a clear code rather than a short one.

**Comment by nloveladyallen** [comment]
> since Electron has its own Node runtime, it should not be affected by a user's Node install

What if a user is running `npm start` instead of using the packager?

**Comment by brrd** [comment]
`npm start` actually runs `electron .` so electron's node will be used anyway.
