### ISSUE TITLE
Ignore YAML-Header

### ISSUE THREAD

**Issue by zommuter** [brrd/Abricotine#142]
Since I'm using [pandoc](https://github.com/jgm/pandoc/), my files usually start with a [YAML-block](http://pandoc.org/MANUAL.html#extension-yaml_metadata_block) such as

```yaml
---
# Here's the document title
title: Document title
---

```
This confuses Abricotine's parser, and if I use YAML-comments (starting with `#`) on a single line, they are interpreted as section headers and thus both confuses the TOC and renders it rather huge. Instead, YAML-headers should be ignored, maybe rendered like comments.

**Comment by darahak** [comment]
This seems a little bit difficult to solve.
Abricotine supports Github-Flavored Markdown and `---` can be used for horizontal rules.

**Comment by brrd** [comment]
I think the best way to do this would be to fork [CodeMirror markdown mode](https://github.com/codemirror/CodeMirror/blob/master/mode/markdown/markdown.js) to add an option `modeCfg.yamlHeader`. By using states, we can set a new `CodeMirror.innerMode` using YAML mode which would be triggered when the document starts with `---` (and closed with another `---`). Then maybe it could be interesting to merge this back to the CodeMirror repo.

This is a huge work, though. I personally would enjoy doing it but I'm not familiar with CodeMirror modes. Maybe later if I get enough time.

**Comment by zommuter** [comment]
@darahak So does pandoc. From a few tests, it seems pandoc does some checks (I tried to [regex it](https://regex101.com/r/HiVfp6/1), but it's not perfect).

I guess `---` is only interpreted as the start (or end) of a YAML-block, if it doesn't make sense as horizontal rule, i.e. when it's not followed by empty lines. Ok, as one can easily check here in the preview, Github-MD doesn't require an empty paragraph after a horizontal rule, so either pandoc does some more checking for a matching YAML-ending (or even whether the potential block contains valid YAML) or it simply requires horizontal rules to be followed by empty paragraphs...

**Comment by brrd** [comment]
@zommuter CodeMirror parser is working line by line so multiline regex won't work. IMO the correct way to do this is definitely to patch markdown mode. I think any other solution would be very tricky, at least in term of performance.

**Comment by dskopa-softdev** [comment]
Front matter YAML block coud appear only at the beginning of the markdown file so it's pretty simple to cut if off from markdown parsing by checking if file starts with `---` and if so, grab anything until next `---` line

**Comment by chris2fr** [comment]
In windows, my YAML front matter is not skipped.

**Comment by brrd** [comment]
@chris2fr What does that mean exactly? Can you describe the issue please.
