### ISSUE TITLE
Can not cancel when closing the app (quit)

### ISSUE THREAD

**Issue by brrd** [brrd/Abricotine#143]
Steps to reproduce:

1. Open a new document and type something (don't save),
2. Open another document and keep it empty,
3. File > Quit,
4. When asked if the first doc must be saved, click "Cancel" => Abricotine closes anyway.

EDIT: it actually also happens when only one document is open and when trying to close the app with the "quit" menu.

**Comment by darahak** [comment]
Is it a regression from the latest merges?
I don't reproduce it: the empty window is closed, but the first one remains.

**Comment by brrd** [comment]
Yes, it behaves like this on develop but the latest stable is OK.

**Comment by brrd** [comment]
Probably related to https://github.com/electron/electron/issues/7977
