### ISSUE TITLE
table alignment by beautyfier missing

### ISSUE THREAD

**Issue by vv01f** [brrd/abricotine#146]
## Table with alignment

| left | center | right |
|:---|:---:|---:|
|foo|bar|0.0|
|barbar|foofoo|10.0|

would be nice if that worked. :)

**Comment by brrd** [comment]
Do you mean you expect this:

```
| left | center | right |
|:---|:---:|---:|
|foo|bar|0.0|
|barbar|foofoo|10.0|
```

to become:

```
| left   | center | right |
| :----- | :----: | ----: |
| foo    |  bar   |   0.0 |
| barbar | foofoo |  10.0 |
```

instead of:

```
| left   | center | right |
| :----- | :----: | ----: |
| foo    | bar    | 0.0   |
| barbar | foofoo | 10.0  |
```

?

**Comment by vv01f** [comment]
(ay)

I would expect:

    | left | center | right |
    |:---|:---:|---:|
    |foo|bar|0.0|
    |barbar|foofoo|10.0|

and:

    | left   | center | right |
    | :----- | :----: | ----: |
    | foo    | bar    | 0.0   |
    | barbar | foofoo | 10.0  |

(or comparable)
to be validated and become:

    | left   | center | right |
    | :----- | :----: | ----: |
    | foo    |  bar   |   0.0 |
    | barbar | foofoo |  10.0 |

**Comment by brrd** [comment]
This will be fixed in the next release, thanks to @FireFragment contribution.
