### ISSUE TITLE
optional line numbers

### ISSUE THREAD

**Issue by vv01f** [brrd/Abricotine#148]
for either all or code-blocks only.

e.g. extra on the left of the editing field, not to be exported.

+ this later can hold other features, e.g. block (un-)collapse

**Comment by nloveladyallen** [comment]
I haven't looked into this, but it should be possible to do with a custom theme.

**Comment by darahak** [comment]
Should probably merge with #97.

**Comment by brrd** [comment]
@nloveladyallen Yes, probably with CSS counters https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Lists_and_Counters/Using_CSS_counters
But it would be better not to depend on themes IMO and to use a global solution with a dedicated option.
And actually CodeMirror has its own option for showing the line numbers, which is not usable through themes.

@darahak Yes!
