### ISSUE TITLE
warnings for possible misinterpretation

### ISSUE THREAD

**Issue by vv01f** [brrd/Abricotine#149]
sometimes I think Markdown is not really well understood, many interpreters have different results. this will lead to me opening a text or md file that will be rendered different in this editor than the author saw it in his.

in #148 there could be shown a warning in such maybe unclear cases. E.g. the numbering issue in lists.

**Comment by brrd** [comment]
I'm sorry I don't really see the use case. What would be the warning with #148? How would it be detected?

**Comment by vv01f** [comment]
maybe far fetched …

e.g. bolds and italics are often misunderstood, many implementations interpret it differently.
if there is a possible doubt due to known different recognition such as

    **this* might be messy* and other nuonces tat actually work in other editors
    instead of
    *__this__ might be messy*

And I guess there are still some other features that can be misinterpreted.

Also #147 can be misinterpreted, a warning-sing could give a hint what is the problem (and maybe later even probable solutions)

**Comment by brrd** [comment]
```
**this* might be messy* and other nuonces tat actually work in other editors
instead of
*__this__ might be messy*
```

I think this example is not valid markdown, the bold is opened but never closed. Is there any specification where it is allowed?

I'm afraid I still don't really get it... Is what you want a linter which underlines differences between markdown implementations? We could try to provide a way to use linters in Abricotine, but in my opinion writing the linter itself is out of the scope of this project.

**Comment by vv01f** [comment]
I do not think it is standard, just it works (somehow) just in single implementations or might give different results at least.

I thought less of linting rather than matching a "known problem" – but probably "out of scope" still fits well.

Would be interesting to compare the (normalized) rendering solutions of competitors with abricotine's still to see what could be a misinplementation or "interpretable". This as well might be more a test/study besides the project.

latest when extended syntax is allowed other such problems might arise or get more complex.

**Comment by brrd** [comment]
> Would be interesting to compare the (normalized) rendering solutions of competitors with abricotine's still to see what could be a misinplementation or "interpretable"

This is why we have specs! Programs should simply follow it, not the opposite.

Abricotine is not reinventing the wheel. It follows [Github Flavored Markdown](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown). Syntax highlighting is provided by [CodeMirror's GFM mode](https://github.com/codemirror/CodeMirror/blob/master/mode/gfm/gfm.js) and markdown is rendered using [Kramed](https://github.com/GitbookIO/kramed), so only GFM is fully supported. If you don't use GFM you could encounter rendering issues. If you find problems with the way Abricotine renders GFM then please create an issue, we would try to fix it.
