### ISSUE TITLE
wrong ELF class: ELFCLASS32 ?

### ISSUE THREAD

**Issue by fahadmehar** [brrd/Abricotine#153]
I have this Issue on my VPS Debian 64 BIT, How I fix this error ?

**Comment by darahak** [comment]
It would be great if you at least gave the complete error message and which version of Abricotine you installed.

**Comment by fahadmehar** [comment]
I have Install Debian 8.7 Jessie  64BIT the Latest one... And I was installing eggdrop with gseen and stats... eggdrop works fine but when i run I got this "Can't load modules gseen: /home/Statistics/eggdrop/modules/gseen.so: wrong ELF class: ELFCLASS32"

**Comment by darahak** [comment]
Still not sure I understand... What does it have to do with Abricotine?

**Comment by fahadmehar** [comment]
What is Abricotine?

**Comment by darahak** [comment]
This is an issue tracker for a Markdown editor called Abricotine.
Where do you think you're posting?

**Comment by fahadmehar** [comment]
So you not deal with Debian OS ... ok sorry
