### ISSUE TITLE
Less border on beginn of editor text

### ISSUE THREAD

**Issue by mica100** [brrd/Abricotine#154]
Both themes (default and default-dark) have a 1cm space on top of the text I can enter. This is wasted display area. As far as I looked it wasn't possible to change this in a theme.less file.

Please add the possiblity to define this in the theme.

May be it's this line in the editor.less file, that needs to get a variable instead of a 50px value:
file: https://github.com/brrd/Abricotine/blob/master/app/less/editor.less

```
    .CodeMirror-code {
        margin-top: 50px;
        margin-bottom: 50%;
    }
```

**Comment by jgclark** [comment]
Seconded.

**Comment by brrd** [comment]
Addind this line in your user-defined theme should solve this issue:

```css
.CodeMirror-code {
   margin-top: 0px;
}
```
