### ISSUE TITLE
Feature Request: Support for assembly of sub-documents

### ISSUE THREAD

**Issue by schaveyt** [brrd/Abricotine#155]
I work as an engineering leader for a large aerospace company we are required to generation massive amounts of technical documents (user manuals, reference manuals, spec sheets, etc) and we are experimenting with the idea of migrating to markdown as a way to store the raw content in git rather than what we have today. 

One key requirement many of our documents have is the ability to break up an enormous document into sub documents with a document that "assembles" them together. We just use this built-in feature of Word to accomplish this.

This allows 1) multiple team members to work on different parts of the document in parallel and 2) isolates change for easier change analysis during reviews.

I have yet to find an markdown editor to do something like this...but holy crap would it be epic!

As a workaround, we have successfully utilized mdmerge from the [MarkdownTools python package](https://pypi.python.org/pypi/MarkdownTools2/1.0) but...this forces us to be relegated back to the old school workflow of type/build/preview...which this markdown editor fantastically eliminates.

Thoughts? What Abricotine even be able to handle the equivalent to an 800pg Word document when it is all merged together?

**Comment by brrd** [comment]
As I understand you want to open several documents in the same editor in order to edit all of them in a single text control and keep different files when saving?

> 1) multiple team members to work on different parts of the document in parallel

I guess if you open all of them in the editor the problem will remains because everybody will be editing the whole text anyway.

Maybe issues #136 and #10 are related to yours?

**Comment by schaveyt** [comment]
To clarify, a document become more/less a folder of .md files with a master .md documents basically instructing the order to assemble. 

For example,

/ SwDevPlan
    /media
    /content
         SwDevPlan_Main.md
         01_Intro.md
         02_ReqMgt.md
         03_Reviews.md
         /Testing
              04_Testing.MD
              04_01_RqmtBased.md
              04_02_Integration.md
         05_Design.MD

The main document is a markdown file that within its content has "include" or "substitutions" to the other sub document files. 

# My Heading

Blah blah blah
Blah blah...

<<[./01_Intro.md]

<<[./02_RqmtMgt.md
...
...
...


The tool would render the content of the referenced subdocuments perhaps surround with a dotted border to indicate a sub doc is present. 

When an edit is made, the edit is store in the sub document.

**Comment by brrd** [comment]
Well, I'm afraid what you need is a custom specific solution... Most people would edit separate .md files and concatenate them with a processor, this is why we are planning feature #136. But inclusions are much heavier to implement. Moreover I'm not really in favor of adding non-standard syntax such as `<<[./01_Intro.md]` in Abricotine. So in my opinion adding this feature to Abricotine would a lot of work for a too specific use case. Sorry.

If you really want to use markdown inclusions you should maybe consider triggering a specific processor on files edit (using something like chokidar or gulp-watch) to build the doc and previewing the output in real time with something like https://github.com/yoshuawuyts/vmd

**Comment by schaveyt** [comment]
Thank you for considering. If the tabs feature is implement that would also go along way to improving our workflow. 
Regards,
