### ISSUE TITLE
No preview for image files with cyrillic symbols in the path

### ISSUE THREAD

**Issue by tri-ton** [brrd/Abricotine#156]
For me preview of images in Abricotine doesn't work if path to the local file contains cyrillic symbols. Otherwise, preview works as it should. There is no such problem with generation of html.

I have Abricotine 0.4.0 on Linux Mint 17, 64-bit. Should I provide any other info?

P.S. Besides that, great editor! Thanks!

**Comment by brrd** [comment]
> Should I provide any other info?

This is enough, thank you. 

It comes from this regex which is too strict: https://github.com/brrd/Abricotine/blob/master/app/renderer/cm-extend-autopreview.js#L67
