### ISSUE TITLE
Adding new item to task list creates regular list item instead

### ISSUE THREAD

**Issue by jacobmischka** [brrd/Abricotine#161]
When hitting enter at the end of a task list item, the next line is automatically populated with a bullet point, but is not automatically populated with the braces to create another task list item. I think it should be assumed that the next list item will also be a task list item.

![peek 2017-03-15 22-58](https://cloud.githubusercontent.com/assets/3939997/23981217/e76ab77c-09d2-11e7-8357-e9f023ee5a58.gif)

Thanks!

**Comment by jacobmischka** [comment]
Interestingly, this works out of the box if you use `-` for bullets intead of `*`.

![peek 2017-03-15 23-19](https://cloud.githubusercontent.com/assets/3939997/23981617/e0fee1da-09d5-11e7-982e-d874e9237f13.gif)

**Comment by brrd** [comment]
This is a duplicate: #43 

By the way I didn't know the `- [ ]` workaround. Interesting.
