### ISSUE TITLE
Toggle bold/italic when selection contains the formatting

### ISSUE THREAD

**Issue by krbaehrle** [brrd/Abricotine#166]
Removing bold or italic by shortcut (or from the menu) works only if only the text inside the `**` is selected.

Example `**Test**`
If `Test` is selected and Ctrl+B pressed, the format will go back to normal `Test`. (okay)
If `**Test**` is selected and Ctrl+B pressed, it will create `****Test****`. (from my point of view that's not handy)

I am not sure if that is the intended behavior or not. If it's intend, then this issue is irrelevant.

**Comment by brrd** [comment]
We can try to fix this.

**Comment by krbaehrle** [comment]
Another related issue when selecting multiple formated parts of a text:
Selection of `**Test** **Test**` plus Ctrl+B will create `****Test** **Test****`  instead of `Test Test.`
