### ISSUE TITLE
[Feature Request] : Auto Saving

### ISSUE THREAD

**Issue by adiultra** [brrd/Abricotine#17]
I thank the developers for the amazing markdown editor. I would like to recommend auto saving documents at any change.

The inspiration is from another electron app [FromScratch](https://fromscratch.rocks/).

**Comment by lrq3000** [comment]
Either autosaving or session saving (ie, store any change to documents even the ones that are not yet saved to a temporary file on disk in Abricotine's user folder, so in case of a crash or just closing the app without saving, everything can be restored).

**Comment by brianmituka** [comment]
+1

**Comment by MAccadia** [comment]
Hi,

I just discovered Abricotine. It feels very clean and simple. I hope it will get attention and support from the open source community. (I wish I could help, but I don't know any JS)

All basic features I wished for are already there, but the auto-save function is essential to me. I was ready to recommend Abricotine to a friend who is going to write her PhD thesis. However, I worry she could lose her work without an auto-save function.

It might be early to recommend Abricotine as it's still in beta. I wish the best for Abricotine and its contributors.
