### ISSUE TITLE
Inconsistent list indentation (2)

### ISSUE THREAD

**Issue by ktcktcktc** [brrd/Abricotine#173]
[Different to #93 ]

The "bullet point" `- ` of a second level list entry will start about where the text starts on the first level. But the **third** level bullet point `- ` will not start where the text of the second level starts. Instead third level entries start far more to the right.

![bildschirmfoto vom 2017-04-02 22-20-28](https://cloud.githubusercontent.com/assets/24965001/24590733/ae4b9604-17f2-11e7-90b6-4e4b56ed10b1.png)

The screenshot is taken with my theme. But it is not a theme issue. It is the same for the default theme.

**Comment by brrd** [comment]
Fixed in version 0.6.0.
