### ISSUE TITLE
Saving is broken on OS X

### ISSUE THREAD

**Issue by altosaar** [brrd/Abricotine#174]
Each time I save (File -> Save), a popup appears saying "The file '*.md' has changed, would you like to reload it?"

I'm not sure how to fix this - any ideas?

Thank you :)

**Comment by brrd** [comment]
I guess we'll need more information about this.

Is the document saved anyway?
Is this happening when you are trying to save a new document or an existing one (or both)?
Is the file name in the popup still '*.md'  when you are trying to save an existing document?
Is the "Save As..." menu working?
When using "Save As...", does the file selection dialog appear before you get the unexpected popup?
What happen when you click "Yes" (e.g. you try to reload the document)?
Is there any error message in the devtools console (hit F12 to open it)?

Finally, is someone else able to reproduce this bug on OSX? (I have no mac to try it where I am right now)

**Comment by altosaar** [comment]
> Is the document saved anyway?

Yes

> Is this happening when you are trying to save a new document or an existing one (or both)?

Both

> Is the file name in the popup still '*.md' when you are trying to save an existing document?

Yes

> Is the "Save As..." menu working?

> When using "Save As...", does the file selection dialog appear before you get the unexpected popup?

Yes & yes

> What happen when you click "Yes" (e.g. you try to reload the document)?

It reloads the document and the cursor goes back to the top of the document.

> Is there any error message in the devtools console (hit F12 to open it)?

No

Hope this helps!

**Comment by nloveladyallen** [comment]
Are you running the binary from Releases or from source?

**Comment by altosaar** [comment]
I'm running this version: https://github.com/brrd/Abricotine/releases/download/0.5.0/Abricotine-osx-x64.zip

**Comment by brrd** [comment]
@altosaar Thanks for those additional informations. This still sounds like a total mystery to me. I can't figure out what happens... :confused: I'll check the source again when I get time.

**Comment by eaglesky** [comment]
I met exactly same issue on my Mac(Version 10.10.5), same program. Is there a workaround for this?

**Comment by brrd** [comment]
@eaglesky I'm sorry but the only workaround that I see now is to use the previous version of Abricotine (0.4.0). I really want to fix this as soon as possible but this is difficult because I can't reproduce this issue...

**Comment by Netherdrake** [comment]
I can confirm the same issue.

Any tips on how to get more information that would help you with debugging?

**Comment by brrd** [comment]
> Any tips on how to get more information that would help you with debugging?

Unfortunately not. I would like to create a special version with some additional logging but I'm really busy now and I can't find the time to do it.

Is this issue happening to every OSX user in 0.5.0?

**Comment by Mottotime** [comment]
Yes. I have the same problem, too.

**Comment by brrd** [comment]
This is obviously a regression introduced with #121. 
On OSX, `handleAsyncFileChange()` is sometimes called after the app saved the document, meaning `abrDoc.pauseWatcher()` is not working properly or in the right time. But I don't really understand what happens exactly...
As I could see, this issue occurs less often when the app is directly run from source.
I'm still looking for a way to fix this...

**Comment by Netherdrake** [comment]
Any updates on the issue?

**Comment by brrd** [comment]
@Netherdrake I began to work on it but this is a huge work and I have no time right now. I'll let you know here if I get some improvement.

**Comment by Netherdrake** [comment]
No problem. I still love the app, and use it *almost* every day.

**Comment by brrd** [comment]
I spent hours looking for a solution and I finally came to the very simple conclusion that chokidar is very slow when used on OSX from an Electron process 😕. The easiest solution I found is to wait a bit (1000 ms) before restarting the watcher once the doc is saved.

Can you build Abricotine from [this branch](https://github.com/brrd/Abricotine/tree/fix-watcher) where I commited the fix in order to confirm you don't encounter this issue anymore?

**Comment by BernsteinA** [comment]
The issue appears to be fixed for me on the `fix-watcher` branch, built on osx 10.12.6

**Comment by Netherdrake** [comment]
Good job @brrd. Looking forward to the new release :)

**Comment by BernsteinA** [comment]
Update: Still happens if I save twice in quick succession. Maybe this would do it?
```
if(this.delayedWatcher) window.clearTimeout(this.delayedWatcher);
        this.delayedWatcher = window.setTimeout(function () {
```

**Comment by brrd** [comment]
@BernsteinA You're right, thanks. This should work better now.
