### ISSUE TITLE
Heading preview broken after code blocks

### ISSUE THREAD

**Issue by brrd** [brrd/Abricotine#176]
Heading is not previewed when it directly follows a code block.

![abr-issue-code-block](https://cloud.githubusercontent.com/assets/7335302/25011376/6d74b470-206d-11e7-87cd-8d6ba2e4b79b.png)

It works well when adding an extra space after the ```.

**Comment by RyanDelGizzi** [comment]
Thanks for the fix in the mean time!

**Comment by brrd** [comment]
@RyanDelGizzi Obviously [CodeMirror 5.25.0](https://github.com/codemirror/CodeMirror/releases/tag/5.25.0) fixed this but I didn't notice it. Thanks for letting me know.
