### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by ffatgit** [brrd/Abricotine#178]
Hello Mr. Brouard;

after I downloaded the Abricotine software and "play" around little bit with it, I recognized how it is possible to translate the software. So I copied the "en.json" rename it to "ge.json" and start flying over the keyboard. After some time the result is the following (hope it is useful and reflects the meaning of the origin. One "special" item: I leaf the original English GNU license and add a German translation behind of it.):

`

{

    "menu-undo": "Rückgängig",
    "menu-redo": "Wiederherstellen",
    "menu-cut": "Ausschneiden",
    "menu-copy": "Kopieren",
    "menu-copy-html": "Kopieren als HTML",
    "menu-paste": "Einfügen",
    "menu-selectAll": "Alles auswählen",

    "menu-help": "&Hilfe",
    "menu-about": "Über Abricotine",
    "menu-visitHomepage": "Homepage besuchen",

    "menu-edit-preferences": "Einstellungen",
    "menu-open-config-dir": "Konfiguration Verzeichnis öffnen",
    "menu-hide": "Abricotine ausblenden",
    "menu-hide-others": "Andere ausblenden",
    "menu-show-all": "Zeige Alle",
    "menu-quit": "Beenden",

    "menu-file": "&Datei",
    "menu-new-document": "Neues Dokument",
    "menu-open": "Öffnen",
    "menu-save": "Speichern",
    "menu-save-as": "Speichern als…",
    "menu-export-html": "Export als HTML",
    "menu-close-document": "Dokument Schließen",
    "menu-close-window": "Fenster Schließen",

    "menu-edit": "&Bearbeiten",
    "menu-find": "Suchen",
    "menu-find-next": "Suchen nächstes...",
    "menu-find-previous": "Suchen vorrieges...",
    "menu-replace": "Ersetzen",
    "menu-replace-all": "Alle Ersetzen",
    "menu-search-clear": "Suche leeren",
    "menu-spelling": "Rechtschreibung",
    "menu-spelling-disabled": "Deaktiviert",
    "menu-brackets-auto-close": "Klammern automatisch schließen",

    "menu-format": "F&ormat",
    "format-italic": "Kursiv",
    "format-bold": "Fett",
    "format-strikethrough": "Durchgestrichen",
    "format-code": "Quellcode",
    "format-heading1": "Überschrift 1",
    "format-heading2": "Überschrift 2",
    "format-heading3": "Überschrift 3",
    "format-heading4": "Überschrift 4",
    "format-heading5": "Überschrift 5",
    "format-heading6": "Überschrift 6",
    "format-list-unordered": "Unsortiere Liste",
    "format-list-ordered": "Nummerierte Liste",
    "format-list-todo": "Aufgaben Liste",
    "format-quote": "Zitat",

    "menu-insert": "&Einfügen",
    "menu-insert-image": "Bild",
    "menu-insert-image-from-computer": "Einfügen von Computer",
    "menu-insert-image-from-url": "Einfügen von URL",
    "menu-image-copy-all": "Alle Bilder in lokalen Ordner kopieren",
    "menu-insert-link": "Link",
    "menu-insert-anchor": "Verweis",
    "menu-insert-codeblock": "Codeblock",
    "menu-insert-math-formula": "Mathmatische Formel",
    "menu-insert-hr": "Horizontale Linie",

    "menu-table": "&Tabelle",
    "menu-new-table": "Neue Tabelle",
    "menu-new-table-2x2": "2 Spalten x 2 Zeilen",
    "menu-new-table-2x3": "2 Spalten x 3 Zeilen",
    "menu-new-table-2x4": "2 Spalten x 4 Zeilen",
    "menu-new-table-2x5": "2 Spalten x 5 Zeilen",
    "menu-new-table-3x2": "3 Spalten x 2 Zeilen",
    "menu-new-table-3x3": "3 Spalten x 3 Zeilen",
    "menu-new-table-3x4": "3 Spalten x 4 Zeilen",
    "menu-new-table-3x5": "3 Spalten x 5 Zeilen",
    "menu-new-table-4x2": "4 Spalten x 2 Zeilen",
    "menu-new-table-4x3": "4 Spalten x 3 Zeilen",
    "menu-new-table-4x4": "4 Spalten x 4 Zeilen",
    "menu-new-table-4x5": "4 Spalten x 5 Zeilen",
    "menu-new-table-5x2": "5 Spalten x 2 Zeilen",
    "menu-new-table-5x3": "5 Spalten x 3 Zeilen",
    "menu-new-table-5x4": "5 Spalten x 4 Zeilen",
    "menu-new-table-5x5": "5 Spalten x 5 Zeilen",
    "menu-table-rows": "Zeilen",
    "menu-table-rows-add-before": "Zeile oberhalb einfügen",
    "menu-table-rows-add-after": "Zeile unterhalb einfügen",
    "menu-table-rows-remove": "Zeile entfernen",
    "menu-table-columns": "Spalten",
    "menu-table-columns-add-before": "Spalte links einfügen",
    "menu-table-columns-add-after": "Spalte rechts einfügen",
    "menu-table-columns-remove": "Spalte entfernen",
    "menu-table-align-left": "Ausrichtung linksbündig",
    "menu-table-align-center": "Ausrichtung zentriert",
    "menu-table-align-right": "Ausrichtung rechtsbündig",
    "menu-table-align-clear": "Ausrichtung zurücksetzen",
    "menu-table-beautify": "Beautify",

    "menu-view": "&Ansicht",
    "menu-view-in-browser": "Dokument in Browser anzeigen",
    "menu-font-size-increase": "Schriftgröße vergrößern",
    "menu-font-size-decrease": "Schriftgröße verkleinern",
    "menu-font-size-reset": "Schriftgröße zurücksetzen",
    "menu-show-menu-bar": "Menüleiste anzeigen",
    "menu-show-table-of-contents": "Inhaltstabelle anzeigen",
    "menu-show-blocks": "Blocks anzeigen",
    "menu-show-hidden-chars": "Zeige versteckte Zeichen",
    "menu-auto-preview": "Automatische Vorschau",
    "menu-auto-preview-images": "Bilder",
    "menu-auto-preview-todolists": "Aufgabenlisten",
    "menu-auto-preview-anchors": "Verweise",
    "menu-auto-preview-math": "Mathematik",
    "menu-auto-preview-iframes": "Iframes",
    "menu-auto-preview-security": "Filter unerlaubter Inhalt",
    "menu-fullscreen": "Vollbild umschalten",
    "menu-theme": "Thema (Theme)",

    "menu-developer": "Entwickler",
    "menu-reload": "Neu laden",
    "menu-reload-theme": "Thema (Theme) neu laden",
    "menu-run": "Befehl ausführen…",
    "menu-devtools": "Entwickler Werkzeuge",
    "menu-open-temp-dir": "Temporären Ordner öffnen",
    "menu-open-app-dir": "Applikations Ordner öffnen",

    "about-title": "Über",
    "about-message": "ABRICOTINE - MARKDOWN EDITOR (v. %0)\n\nCopyright (c) 2015 Thomas Brouard\n\n* Original *\n\nThis program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 3 of the License, or (at your option) any later version.\n\nThis program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.\n\nYou should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.\n\n* Übersetzung *\n\nDieses Programm ist freie Software. Sie können es unter den Bedingungen der GNU General Public License, wie von der Free Software Foundation veröffentlicht, weitergeben und/oder modifizieren, entweder gemäß Version 3 der Lizenz oder (nach Ihrer Option) jeder späteren Version.\n\nDie Veröffentlichung dieses Programms erfolgt in der Hoffnung, daß es Ihnen von Nutzen sein wird, aber OHNE IRGENDEINE GARANTIE, sogar ohne die implizite Garantie der MARKTREIFE oder der VERWENDBARKEIT FÜR EINEN BESTIMMTEN ZWECK. Details finden Sie in der GNU General Public License.\n\nSie sollten ein Exemplar der GNU General Public License zusammen mit diesem Programm erhalten haben. Falls nicht, siehe <http://www.gnu.org/licenses/>.",

    "new-document": "Neues Dokument",
    "confirm-close-title": "Ungespeichertes Dokument",
    "confirm-close-message": "Änderung am Dokument '%0' vor dem schließen speichern?",
    "confirm-save-and-close": "Speichern und Schließen",
    "confirm-close-without-saving": "Schließen ohne zu speichern",

    "dialog-open": "Dokument öffnen",
    "dialog-save": "Dokument speichern",
    "dialog-save-message": "Das aktuelle Dokument muss gespeichert werden, bevor diese Aktion ausgeführt werden kann.",

    "reset-dialog": "Abricotine - Konfiguration Aktualisierung",
    "reset-dialog-message": "Die aktuelle Konfiguration ist veraltet und muss aktualisiert werden. Möchten Sie die Abricotine Konfiguration zurücksetzen? \n\nWARNUNG: Ihre vorherige Konfiguration (inklusive Anwender Themen (Themes), Vorlagen und Wörterbüchern) geht verloren.",

    "button-ok": "OK",
    "button-no": "Nein",
    "button-yes": "Ja",
    "button-yes-recommended": "Ja (Empfohlen)",
    "button-cancel": "Abbrechen",
    "button-save": "Speichern",

    "insert-image": "Bild einfügen",
    "insert-image-filter": "Bilder",

    "permission-denied": "Keine Berechtigung",
    "permission-denied-message": "Die Datei '%0' konnte nicht geschrieben werden: Keine Berechtigung . Bitte wählen Sie einen anderen Pfad.",

    "images-copied": "Bilder kopiert",
    "images-copied-message": "Dokument Bilder wurden in das Verzeichnis '%0' kopiert.",

    "html-export-title": "Abricotine Dokument",

    "changed-file": "Geänderte Datei",
    "changed-file-message": "Die Datei '%0' Wurde von einem anderen Programm verändert. Möchten Sie es neu laden?",

    "file-deleted": "Gelöschte Dateien",
    "file-deleted-message": "Die Datei '%0' existiert nicht mehr. Die Datei im Editor behalten?",

    "pane-table-of-contents": "Inhaltsverzeichnis"
}

`

best regards
Frank

**Comment by brrd** [comment]
Thank you very much for your contribution! Do you think you could submit it in a pull request?

By the way I think the [ISO code](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) for German is not "ge" but "de". 

Concerning the license, most of the time we only keep the English version but I let you decide which solution is better.

**Comment by ffatgit** [comment]
Hello brrd

yes you are right "ge" is wrong and "de" is the right term.
I wasn't sure with the license; as explained before. So let's kill the German translation.
To your question of "pull request"; yes I would do it; but I'm "Only a interested user" and no developer; so I have not the knowledge. (I tried it, but the right way wasn't clear to me). I'm really sorry.
So please fell free to "integrated" the translation by your on.
Have a nice evening!

**Comment by brrd** [comment]
> To your question of "pull request"; yes I would do it; but I'm "only a interested user" and no developer; so I have not the knowledge. (I tried it, but the right way wasn't clear to me). I'm really sorry.

Don't be sorry, that's not a problem, I'll do it. 
Thank you very much for your contribution!

**Comment by brrd** [comment]
:open_mouth:... Actually I just remembered that the German translation was added two weeks ago by @oyox: https://github.com/brrd/Abricotine/blob/develop/default/lang/de.json
So it's already done and it will be available in the next release of Abricotine!
