### ISSUE TITLE
Accelerator keys in win32-x64 not raising menus

### ISSUE THREAD

**Issue by Munchotaur** [brrd/Abricotine#18]
When I press an accelator for one of the menus in Abricot in Win7, for example Alt-V for 'View', the accelator is displayed in the menu bar as the usual underline character, but the menu itself isn't displayed.

Menus work properly via the mouse however.

**Comment by brrd** [comment]
This is probably related to this issue with Electron: https://github.com/atom/electron/issues/2504

**Comment by Munchotaur** [comment]
Yes, it sounds like the same behaviour.

**Comment by brrd** [comment]
I'm closing this issue as wont fix since it does not depend on Abricotine.
