### ISSUE TITLE
Changing the editor's font family

### ISSUE THREAD

**Issue by alexcheninfo** [brrd/Abricotine#19]
Great app! I've been looking for something like this for ages.

I wanted to change the font family of the editor (the writing area) so I added this to `config.json`:

```
  "editor": {
    "font-size": "16px",
    "font-familiy": Inconsolata
  },
```

However, nothing happened.

Is this a bug? Or there's another way of doing it?

**Comment by casidiablo** [comment]
That does not look like valid JSON actually.

**Comment by brrd** [comment]
It is not working because this option does not exist in Abricotine.
Styles customization (including font family) is not supported yet, but this feature is planned for later development. See #9.
