### ISSUE TITLE
Abricotine can not start in Ubuntu

### ISSUE THREAD

**Issue by Mottotime** [brrd/Abricotine#193]
Hi, I installed Abricotine 0.5.0 using Abricotine-linux-ubuntu-debian-x64.deb on Ubuntu  16.04.2. 

Recently I can not start Abricotine any more. 
If I start it in the terminal, there is an error shows:

```shell
>> Abricotine                                             
(node:3740) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Error processing argument at index 0, conversion failure from #<Object>
(node:3740) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

I tried to reboot the Ubuntu and reinstall the Abricotine, but these do not work.

Would you please help me about this error?
Thanks a lot.

**Comment by brrd** [comment]
Please see #163.

**Comment by Mottotime** [comment]
Thank you very much.
