### ISSUE TITLE
Link rendering error

### ISSUE THREAD

**Issue by MatteoCampinoti94** [brrd/abricotine#195]
As seen in the screenshots below every time there is an open square bracket '[' everything between it and any closed square bracket ']' or the EOF (like in the second case pictured) is rendered as link
![screenshot](https://user-images.githubusercontent.com/5142004/27870125-57ce060a-61a2-11e7-92a6-3385b415068c.png)
![screenshot](https://user-images.githubusercontent.com/5142004/27869537-8b19bb3c-61a0-11e7-961f-0dd2ff279df9.png)

The bug does not transfer to html output, it is present only when rendering inside Abricotine.

Not sure how Abricotine handles parsing for rendering but this bug could be fixed by looking for a closed square bracket ']' and a pair of brackets '( )' after the first '['.

**Comment by brrd** [comment]
I don't reproduce this issue.

![image](https://user-images.githubusercontent.com/7335302/27870608-9522ebc8-61a3-11e7-8a7e-8ceae1f3c68f.png)

Which version do you use? What is your OS?
Can you provide a full sample markdown file?

**Comment by MatteoCampinoti94** [comment]
Am on Arch Linux and using latest 5.0 version from AUR

To reproduce try removing '(url)'
For example try:
```
Hello [ world
Hello ] world
```
And also:
` [hello] [world]`
In this case it seems to consider the second pair of '[]' as the second part of the link instead of looking for matching '()'

The bug only occurs when there isn't a closing ']' or if there aren't any matching pairs '()'.

**Comment by MatteoCampinoti94** [comment]
You were right.
Problem is with AUR version. It must be out of date.

Sorry for the mistake.

**Comment by brrd** [comment]
Well... I can reproduce it partially.

![image](https://user-images.githubusercontent.com/7335302/27871411-e3246a70-61a5-11e7-87f7-9d6939eb4d7a.png)

Anyway, it looks like an issue with CodeMirror markdown mode. Could you find any refrence to this issue in https://github.com/codemirror/CodeMirror/issues ?

**Comment by MatteoCampinoti94** [comment]
I'll look into it.

Also checked the AUR page and it uses the current 0.5.0 source code. It doesn't change it, just builds the package for Arch. Not sure why a bug like this would occur in this case and not using the app directly from the git repo.

**Comment by MatteoCampinoti94** [comment]
Built the 0.5.0 version and the bug is indeed present there. It was fixed in the meantime it seems.

**Comment by MatteoCampinoti94** [comment]
Now this is weird. If I use the linux 64bit binaries from here [0.5.0/Abricotine-linux-x64.tar.gz](https://github.com/brrd/Abricotine/releases/download/0.5.0/Abricotine-linux-x64.tar.gz) then the bug is not present.

What version of npm and Node.js was it built with?

**Comment by MatteoCampinoti94** [comment]
I've looked into CodeMirror open issues but couldn't find anything specific to this.
I did find these two though:
[/issues/4456](https://github.com/codemirror/CodeMirror/issues/4456) This one seems to relate to incorrect brackets matching. Doesn't seem to be the problem I've found though.
[/issues/4501](https://github.com/codemirror/CodeMirror/issues/4501) This one seems to be the closest to what happened with me.

**Comment by MatteoCampinoti94** [comment]
Found it in the closed issues!
[/issues/4735](https://github.com/codemirror/CodeMirror/issues/4735)
The bug has already been patched on the 9th of May though so not sure how it could still happen to me.

**Comment by MatteoCampinoti94** [comment]
Will try to merge the patch and see if the problem still occurs.

_Sent from my Nextbit Robin using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MatteoCampinoti94** [comment]
Can't find anything that causes the problem.
Though tbh am not sure I found all the parts of the code responsible for recognizing a link/image.

**Comment by brrd** [comment]
I finally understood what happens!

I can reproduce this bug there: http://codemirror.net/demo/simplescrollbars.html. On that page, CodeMirror version is "5.27.5".

On my build of Abricotine, CodeMirror version is "5.24.2" (you can see it by opening the devtools (F12) and calling `CodeMirror.version` in the console).

In `package.json`, version is ` "codemirror": "^5.24.2"`, which means any 5.x.x version upper to 5.24.2 and lower to 6.0.0.

Obviously some regression was introduced in CodeMirror markdown mode since version 5.24.2 and this buggy version was the latest available when AUR package was build. This explains why we find different behaviors between builds.

So IMO the correct way to fix this would be to submit an issue in CodeMirror and update the build it when this issue is fixed.

**Comment by MatteoCampinoti94** [comment]
That's great to hear!
Well, great cause we now know what happened and not that great cause we can't really do much about it XD
Hopefully it'll be fixed soon.

My compliments for your investigative work though!
I'll open an issue in CodeMirror repo tomorrow if you won't have done it already.

**Comment by MatteoCampinoti94** [comment]
[Comic: Tough love p5]

**Comment by MatteoCampinoti94** [comment]
Sorry, wrong button
