### ISSUE TITLE
Feature request: Verify links and clickable links

### ISSUE THREAD

**Issue by agirorn** [brrd/Abricotine#200]
Feature request: Verify links and clickable links

## Verify links

It would be nice if Abricotine could verify links and show a red underline for links have not been defined and are invalid. Also, every link could be checked if it actually exists.

```markdown
[NotDefinedLink] The link is referring to reference that is not defined. 
[some website][NotDefinedLink] The link is referring to reference that is not defined. 

[BrokenLink] The link is referring to a broken link. 
[some website][BrokenLink] The link is referring to a broken link. 

[ValidLink] This should be ok.
[GitHub website][ValidLink] This should be ok.
[GitHub website](https://github.com/) This should be ok.

[BrokenLink]: https://some-broken-link.com/
[ValidLink]: https://github.com/
```

## Clickable links

It would be nice if I could hold down the [Alt] key when hovering the cursor over valid links and they would get underline and be clickable. This will help when pages are very long and all the links are defined at the bottom.

```markdown
[stackoverflow] Link to https://stackoverflow.com/. 
[stackoverflow][stackoverflow] Link to https://stackoverflow.com/. 

[stackoverflow](https://stackoverflow.com/) Link to https://stackoverflow.com/.

[stackoverflow]: https://stackoverflow.com/
```

**Comment by nloveladyallen** [comment]
How do you define a "broken" link? Send an HTTP request and see if the server doesn't respond or returns an error code? If the user is offline, is every link then marked as broken? Or if the server responds with 403, that could very well be how it's supposed to respond to a request without the proper cookies.

**Comment by brrd** [comment]
Please create one separate issue for each feature request.

Verify links: #201  
Clickable links: #198 (duplicate)
