### ISSUE TITLE
Any new windows releases ?

### ISSUE THREAD

**Issue by nickbe** [brrd/Abricotine#204]
There seem to be lots of enhacement which are not part of the old release yet.
Are there newer windows releases available somewhere?

Cheers
Nick

**Comment by brrd** [comment]
I'm really busy now, but I will do it as soon as I get a couple of free hours.
You can [build the app from source](https://github.com/brrd/Abricotine/blob/master/docs/installation-and-usage.md#building-and-packaging) if you really don't want to wait.

**Comment by nickbe** [comment]
Ok. I'll try to do that, but I have no experience whatsoever with node.js.

**Comment by nickbe** [comment]
Just wanted to mention that I just created the windows binaries by following the howto. It worked flawlessly with the current development version. Thanks 😄
