### ISSUE TITLE
Abricotine , don not have windows-x86.exe ?

### ISSUE THREAD

**Issue by redstoneleo** [brrd/Abricotine#205]
Abricotine , don not have windows-x86.exe ?

**Comment by brrd** [comment]
As mentioned in https://github.com/brrd/Abricotine/releases:

> Windows 32 bits installer depends on users contributions (please submit binaries in #89).

**Comment by redstoneleo** [comment]
Abricotine 0.5.0 released with Abricotine-windows-x64.exe, but no Abricotine-windows-x32.exe or Abricotine-windows-x86.exe, Abricotine-windows-x64.exe installed failed on my win7 32 bit machine

**Comment by brrd** [comment]
What don't you understand in my previous post?
Nobody released this binary, so it is not available. If you want to build and submit it, you can do it. Then it would be available.

> Abricotine-windows-x64.exe installed failed on my win7 32 bit machine 

Abricotine-windows-x64.exe is not compatible with 32 bit OS.
