### ISSUE TITLE
Feature: Project Tree View

### ISSUE THREAD

**Issue by nathanlesage** [brrd/Abricotine#212]
It would be great, if one would have the option to open a folder containing lots of .md-files to have them show up in a sidebar and switch to them more easy. Background: If you tend to store information in several .md-files and need to quickly scroll past all files to find the information you need, it is a lot easier doing it in one window instead of multiple windows having several different windows open.

Desired behavior: One has the option to "Open folder ...", which results in the folder opening up in a sidebar showing only .md-files (and sub-folders with their md-files). With one click one is then able to change the contents of the main window to the contents of the selected .md-file, work with it or just use search etc. If another file is clicked, the currently opened file is closed and the newly selected is opened instead in the same window. If I close the app and re-open it the folder should then be restored.

This would be a behavior much like Ulysses, with the exception that Abricotine is generally better, b/c open source. If I find the time I will try to do some of the work myself!

**Comment by brrd** [comment]
I think it's a duplicate: #136
