### ISSUE TITLE
`Pos1` isn’t line-specific

### ISSUE THREAD

**Issue by fbruetting** [brrd/Abricotine#216]
While `End` always jumps to the end of the current _displayed_ line, `Pos1` jumps to the beginning of the “real” line.

**Comment by brrd** [comment]
This regression was introduced in d64aec3b765b252cd09a8e039ba9d323967d17a0 and is fixed on the develop branch since 5ccfee00831eb3e882954ddfa015c40cd66e044e. It will be available in the next release.
