### ISSUE TITLE
Unsaved work : Cancel do not work every time when exit without previously 'Save'

### ISSUE THREAD

**Issue by Jumanjii** [brrd/Abricotine#217]
Os: macOS 10.13.2
Version: 0.6

When exiting Abricotine (close window or cmd-Q),
an alert appears with the message "Do you really want to close 'New Document' without saving?"

If click on cancel, sometimes the windows disappear and the text wrote can't be recovered.

**Comment by brrd** [comment]
Duplicate : #143
