### ISSUE TITLE
highlight.js broken in HTML

### ISSUE THREAD

**Issue by thj01** [brrd/Abricotine#219]
the HTML out from code doesn't work with highligt.js

higlight.js wraps the code in `<pre><code class="foo">` tags

and abricotine exports it as a `<p>`

**Comment by brrd** [comment]
Here again we will need more info. Please give an example:

* What do you write in the app?
* What source HTML do you get when exported?
* What HTML do you expect?

Please also check your browser console when previewing the HTML since higlhight.js and MathJax are loaded from remote CDN and may not work if your Internet connection is not able to reach those CDN.

**Comment by thj01** [comment]
Thank you for the quick response :) Here are som details

input in abricotine (with ` )
```
for i in range(1.7):
    print(i)
```
output in HTML
```
<p><code>for i in range(1,7): 
	print(i)</code></p>
```
The output in he browser is not styled by highlight.js

if i remove the styling script in template.html with the lines from the website (https://highlightjs.org/usage/) it doesn't highlight the code.
According to the website code must be inside a `<pre class=""><code>` element to be shown.

I have made an example that works with both latex and highlight.js:

```
<!doctype html>
<html>
    <head>
        <title>Abricotine Document</title>
        <meta charset='utf-8'/>
        <link rel="stylesheet" type="text/css" href="./preview.html_files/styles.css">
        <script src="./preview.html_files/toc.js" type="text/javascript"></script>

        
        <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.2.0/styles/default.min.css">
		<script src="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.2.0/highlight.min.js"></script>
		<script>hljs.initHighlightingOnLoad();</script>
		
		<script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML"> </script>
    </head>
    <body>
	
		<p><span class="latex_inline"> \( x = \frac{-b \pm sqrt D}{2a} \) </span></p>

		<div class="latex_block">$$ x = \frac{-b \pm sqrt D}{2a} $$</dic>
			
		<pre>
			<code class="">
		for i in range(1,7): 
			print(i)
			</code>
		</pre>

    </body>
</html>

```

**Comment by brrd** [comment]
Highlight.js won't guess the language. Please try:

    ```python
    for i in range(1,7): 
        print(i)
    ```

**Comment by brrd** [comment]
And actually, in markdown \` is the formatting for inline code, so `<p><code>` is the expected output. To display code in a block, use tabulations or ```.
