### ISSUE TITLE
Danish Translation

### ISSUE THREAD

**Issue by thj01** [brrd/Abricotine#221]
I have made a translation for danish. How can i upload it?

**Comment by brrd** [comment]
You must create a fork of Abricotine, commit your changes on the develop branch of your fork and finally submit a pull request targeting the main Abricotine repo. 

You can find many tutorials on the Internet if you don't know how to do. For instance, I find that one really clear: https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/
