### ISSUE TITLE
Suddenly no automatic indention any more

### ISSUE THREAD

**Issue by nickbe** [brrd/Abricotine#223]
When typing an asterisk in a list, the editor created an automatic indention. But after reinstalling abricotine this functionality has gone and the asterisk stays at the start of a line.
Is this a change on purpose?

Also is there a newer build for windows? (newer than 0.60)

**Comment by brrd** [comment]
> When typing an asterisk in a list

Do you mean "When typing an asterisk *to create* a list"?

> But after reinstalling abricotine this functionality has gone and the asterisk stays at the start of a line.

Try adding a space after the asterisk. 
If this doesn't solve your problem, please provide an explicit screenshot.

> Also is there a newer build for windows? (newer than 0.60)

Not yet. Everything is there: https://github.com/brrd/Abricotine/releases

**Comment by brrd** [comment]
Try to refresh the theme (CTRL+F5) and maybe to restart the app after refresh.

**Comment by nickbe** [comment]
Hey that did work :)
Since the problem remained between system reboots and different sessions, Ctrl-F5 must do something magical here 😉

**Comment by brrd** [comment]
👍 
No magic here. Version 0.6.0 introduced some changes in styles. For performance concern styles are kept in cache. CTRL+F5 just empties this cache and recomputes the styles.

**Comment by nickbe** [comment]
Ok, so problem is solved, but the problem remains and I don't think it makes sense to be aware of CTRL F5 as something you have to do regularly to prevent problems :wink

**Comment by brrd** [comment]
> Ok, so problem is solved, but also remains because I don't think it makes sense to be aware of CTRL F5 as something you have to do regularly to prevent problems 😉

I opened #224 to fix this.

**Comment by nickbe** [comment]
Perfect .
So switching from one version to another caused the problem in the first place. Got it.
Thanks
