### ISSUE TITLE
Syntax highlight for shell code does not work

### ISSUE THREAD

**Issue by 73** [brrd/Abricotine#229]
Hi,
first of all: Thank you for my favorite markdown editor.
I think I found a bug.

I'm on Abricotine 0.6.0 on Ubuntu 17.10.
There seems to be no syntax highlight for shell code:
![screenshot from 2018-02-03 13-26-14](https://user-images.githubusercontent.com/529346/35767114-1389a12a-08e6-11e8-85f4-0b7326dc448f.png)

It should look like:
```sh
# comment
ls
```

```json
{ "order": 4711 }
```

Best regards
-- 73

**Comment by brrd** [comment]
See https://github.com/brrd/Abricotine/blob/master/docs/configuration.md#highlight-modes

In config.json add the key: `"highlight-modes": "shell"` and restart the app.

**Comment by 73** [comment]
Shoot. You're right, did it at work forgot it at home. My bad.
Thank you!
