### ISSUE TITLE
Lines-wrapping in lists

### ISSUE THREAD

**Issue by tmr232** [brrd/Abricotine#23]
When a list item is line-wrapped, the line generated by the wrap is not indented. This seems very confusing.

![image](https://cloud.githubusercontent.com/assets/1386239/13254966/7a0442a4-da4c-11e5-8640-dda0762164e7.png)

Indenting it to match the start of the line will look better, as it will be clearer that it is part of the original line.
![image](https://cloud.githubusercontent.com/assets/1386239/13254988/992f1f5a-da4c-11e5-9a33-e49283a8cbcb.png)

**Comment by krbaehrle** [comment]
Agree 100%. For very long list entries, that need even more than two lines, it is very confusing.

**Comment by krbaehrle** [comment]
The problem applies also to quotes `> `.
