### ISSUE TITLE
Provide an unzippable Windows version

### ISSUE THREAD

**Issue by ogregoire** [brrd/Abricotine#233]
It'd be nice to put Abricotine on a USB stick and be able to run it as is on a Windows platform, without the burden of installing it.

**Comment by brrd** [comment]
Duplicate: #74

**Comment by RoyiAvital** [comment]
@brrd , Is there, at the moment option to have the configuration files at the installation folder?

Thank You.

**Comment by brrd** [comment]
@RoyiAvital see #74.
