### ISSUE TITLE
Release for Flatpak

### ISSUE THREAD

**Issue by victorpaleologue** [brrd/Abricotine#235]
Thanks for this nice piece of software !
Could we have it available as a Flatpak (for Linux) ?
The advantage is that all similar OSes will be able to run a binary release, without requiring you to package it for every platform.
It can then be distributed through [Flathub](https://flathub.org/), also.

**Comment by brrd** [comment]
This is a duplicate. I explained in #78 the reasons why Flatpak is currently not in our plans.
