### ISSUE TITLE
Support diagrams

### ISSUE THREAD

**Issue by Ayc0** [brrd/abricotine#237]
This is a feature request

Possibility to support some diagrams such as in this [example](http://support.typora.io/Draw-Diagrams-With-Markdown/)
Or allow some extensions

**Comment by nanochap** [comment]
One js library for drawing the flowchart is `Mermaid`

**Comment by dskopa-softdev** [comment]
Another option is Graphviz syntax
vscode has a plugin to preview that
https://marketplace.visualstudio.com/items?itemName=geeklearningio.graphviz-markdown-preview

**Comment by viaregio** [comment]
vscode has a plugin to preview mermaid graphs too:
https://github.com/mjbvz/vscode-markdown-mermaid

**Comment by brrd** [comment]
This issue actually depends on #51.

**Comment by csebille** [comment]
Hi,
  As I already worked on this very subject for my own needs, I have written a tutorial to show mermaid diagrams into document exported as HTML.

  I understand it doesn't answer the use case of seeing diagrams directly into the editor but it might help.

Regards,

Christophe
