### ISSUE TITLE
Abricotine is the default editor for unexpected file types

### ISSUE THREAD

**Issue by ayaankazerouni** [brrd/abricotine#239]
_This may not be an Abricotine issue specifically, so maybe this is not the right place._

When I open certain files, they open in Abricotine by default, even though they are not Markdown files (js, java, json). The issue is that Abricotine has somehow taken highest priority as a "text-editor" as opposed to being a "Markdown editor", and I have to manually set the default editor for these filetypes. This is not ideal.

I'm not certain how to address this, both on my own system, and in the Abricotine settings.

**Comment by brrd** [comment]
Not sure it is related to Abricotine, maybe it comes from https://github.com/unindented/electron-installer-debian/

Abricotine is supposed to be associated to markdown files only. See: https://github.com/brrd/Abricotine/blob/970a66460353023a46e0e071bdf23daa807c9335/scripts/deb.js#L17

This issue needs further investigation...
