### ISSUE TITLE
Can not type 'L' without caps lock on Linux

### ISSUE THREAD

**Issue by Jumanjii** [brrd/Abricotine#240]
Hi,

I tried to figure it out myself in the code but do not so, I'm making an issue while I'm still investigating.
On Linux (Ubuntu), it's impossible to write 'L' without caps lock.

When you use "Shift+L", the result is it's selecting the current block.

Can you reproduce this issue?

**Comment by brrd** [comment]
I guess you are building the app from the develop branch?
It's an issue introduced in 08b5b0f8200c040735c307b3ddc5bb4038d8c761, I will check the new keybindings again. 
Thanks for reporting.

**Comment by Jumanjii** [comment]
Oh yeah, I searched for "Shift+L" and did not be aware of "Shift-L" for mac keybinding :-)

**Comment by brrd** [comment]
Actually we use two different libs to manage hotkeys in Abricotine, and each has its own syntax: "Shift+L" is for Electron, "Shift-L" for CodeMirror.

**Comment by Jumanjii** [comment]
<3
