### ISSUE TITLE
Need to install libXScrnSaver-1.2.2-14.fc28.x86_64 in Fedora 28

### ISSUE THREAD

**Issue by murpholinox** [brrd/Abricotine#246]
Otherwise it won't open.

**Comment by brrd** [comment]
This is a known issue with Electron: https://github.com/electron/electron-quick-start/issues/69
Since there is no official rpm package release, I guess what you are asking for is an addition about this in the documentation?

**Comment by murpholinox** [comment]
Yes. Thank you very much.
