### ISSUE TITLE
Menu not working in KDE Plasma with global menu

### ISSUE THREAD

**Issue by marrcelo** [brrd/Abricotine#249]
I'm using global menu of KDE Plasma and I can't use any of the options in menu of Abricotine menu.

**Comment by brrd** [comment]
Related to https://github.com/electron/electron/issues/8455, obviously fixed in Electron 1.6.12-beta. 
We already updated Electron version 1.6.2 to 1.8.2, so it should work when building the app from the develop branch, and it will be fixed in the next release.
