### ISSUE TITLE
strange issue : easter egg ?

### ISSUE THREAD

**Issue by Hugo-Trentesaux** [brrd/Abricotine#250]
I was editing a markdown file in Abricotine (v. 0.6.0) and I inserted the link :

    [text](video/video.avi)

I accidentally Shift+Clicked the link, it opened my browser to 

    https://movies.disney.com

Strange...

**Comment by brrd** [comment]
Looks like http://video/video.avi (and more generally http://video) redirects to https://movies.disney.com...

**Comment by Hugo-Trentesaux** [comment]
So strange ! Because I tried video/video.avi in my URL and found nothing. Nothing to do with Abricotine, sorry :D
