### ISSUE TITLE
"The package is of bad quality."

### ISSUE THREAD

**Issue by stanwmusic** [brrd/Abricotine#252]
On Ubuntu14.04   I downloaded  Abricotine-0.6.0-ubuntu-debian-x64.deb  and opened it with Ubuntu Software Center (which I rarely ever use)  But I get the error:

The package is of bad quality.
The installation of a package which violates the quality standards isn't allowed. This could cause serious problems on your computer. Please contact the person or organisation who provided this package file and include the details beneath.
-----------------------------
Lintian check results for /home/stan/Downloads/abricotine-0.6.0-ubuntu-debian-x64.deb:
E: Abricotine: bad-package-name
E: Abricotine: package-not-lowercase

As a long shot  I renamed the package to start with a  lower case  a (abricotine)  but  of course to no avail.
------------------------------
I could have ignored warning and install it, but I am curious if other's have  experienced this and if so why I couldn't find it on Google  DuckDuckGo or Bing. 

I just  installed it with Gdebi  Package Installer and it gave no warnings and installed fine, and Abricotine is open and working. 

I just thought I would report my experience with the Ubuntu Software Center just in case this  is beneficial to the developers etc..

**Comment by brrd** [comment]
IMO avoiding uppercase in package names (and therefore command names) is definitely a good practice. I didn't pay attention to this when I created Abricotine, but now I think renaming the app in full lowercase would be a good idea.

**Comment by brrd** [comment]
This was fixed in version 1.0.0.

**Comment by stanwmusic** [comment]
Sorry you had that problem, It is a wonderful program and very useful .
