### ISSUE TITLE
Feature Request: Close YAML-header with `...`

### ISSUE THREAD

**Issue by seifferth** [brrd/Abricotine#267]
Pandoc's syntax allows the use of `...` as an alternaive to `---` for closing YAML-headers, so this would be a valid document:

```
---
title: Document Title
author: Document Author
...

Document body in *markdown* starts here.
```

Would it be possible to treat this way of specifying YAML-headers the same as the currently supported way? This relates to #142 and #255.

**Comment by brrd** [comment]
It relies on CodeMirror's yaml-frontmatter mode, so the first step to solve this would be to develop this feature in CodeMirror: https://github.com/codemirror/CodeMirror

* yaml-frontmatter mode source: https://github.com/codemirror/CodeMirror/blob/master/mode/yaml-frontmatter/yaml-frontmatter.js
* yaml-frontmatter demo: https://codemirror.net/mode/yaml-frontmatter/index.html

**Comment by seifferth** [comment]
Thanks for the hint. I finally got around to opening a [topic on the CodeMirror discussion board](https://discuss.codemirror.net/t/pandoc-markdown-style-yaml-frontmatter/2182). I'll get back here once there is news from the CodeMirror side of things.

**Comment by seifferth** [comment]
The feature was merged into CodeMirror today. See <https://github.com/codemirror/CodeMirror/pull/6020>. So I guess this issue will resolve itself with the next CodeMirror update.
