### ISSUE TITLE
CPU overheating

### ISSUE THREAD

**Issue by didierCH** [brrd/Abricotine#275]
When starting Apricotine on Linux Mint 19.2 the fan's will go on full speed, the CPU's are nearly at 100% percent and the heat of my processors goes around 100° Celsius. Yesterday it shut of the laptop because of overheating.

**Comment by brrd** [comment]
Thanks for reporting. Is this issue related with #274?

**Comment by didierCH** [comment]
Thanks for the fast response. I don't know if it's related with #274 but I don't think so. The CPU load is high right from the start of Apricotine without any open file. I don't know how to inspect the whole thing because I have no clue about Electron. But If you have a hint for me I try to get you more information about this.

**Comment by didierCH** [comment]
I have to ad a great thank you for creating Abricotine. In my opinion it is the best markdown editor around! Merci beaucoup!

**Comment by brrd** [comment]
Thank you very much. 

Monitoring performances could help fixing this issue.

*

**Comment by didierCH** [comment]
Hi @brrd 
Attached you will find a console log of 4 seconds after opening Abricotine. When I interpret it right it does nothing, but the heat of my CPU explode to 100° C. I tested on a Mac too, everything seems fine there. My System Linux Mint 19.2
[abricotine-cpu-overheating.json.zip](https://github.com/brrd/Abricotine/files/3846662/abricotine-cpu-overheating.json.zip)

**Comment by brrd** [comment]
Thank you for your feedback. Could you please try version 0.6.0 (https://github.com/brrd/Abricotine/releases/tag/0.6.0) and tell if this issue also occurs in this version?

**Comment by didierCH** [comment]
Tried version 6 and the issue doesn't occur. Thanks, that means I can continue to use Abricotine in my daily work.

**Comment by brrd** [comment]
@didierCH thank you for your feedback which is really helpful.

So this comes from any of those changes: https://github.com/brrd/Abricotine/compare/0.6.0...0.7.0

Possibly related: https://github.com/electron/electron/issues/20233

**Comment by brrd** [comment]
@didierCH Is it better in version 1.0.0?

**Comment by didierCH** [comment]
Hi @brrd it looks way better. Although it starts high (temperature goes up to 94 °C at start) but after 10 to 20 seconds the temperature goes back to a normal level.

**Comment by brrd** [comment]
Glad it helped!

**Comment by didierCH** [comment]
Thank you for your hard work!
