### ISSUE TITLE
Enhancement request: Ability to 'embed' audio files

### ISSUE THREAD

**Issue by andrebenrubi** [brrd/Abricotine#280]
<audio src="_audio/*.mp3" controls></audio>

**Comment by brrd** [comment]
This is already possible. Just add soundcloud.com (or similar service) to the list of [allowed domains in your configuration file](https://github.com/brrd/Abricotine/blob/develop/docs/configuration.md#autopreview-domains), enable autopreview for iframe and paste into the editor the HTML snippet provided by soundcloud.

**Comment by andrebenrubi** [comment]
Thanks for the quick reply.

Looking at local files in subfolder not one that is on the web.

André

**Comment by brrd** [comment]
It makes sense. I created a new issue for this: #281.

**Comment by andrebenrubi** [comment]
Thank you!
