### ISSUE TITLE
[Regression 0.7 -> 1.0] code blocks are not highlighted anymore

### ISSUE THREAD

**Issue by actionless** [brrd/Abricotine#282]
Code block (```) is not anymore highlighted and neither have any HTML class which could be used for a custom CSS.

0.7:
![2020-04-25--1587788112_708x1018_scrot](https://user-images.githubusercontent.com/1655669/80271137-97af2400-86bd-11ea-8cfb-c960f341c07b.png)

1.0:
![2020-04-25--1587788529_790x1018_scrot](https://user-images.githubusercontent.com/1655669/80271139-9a117e00-86bd-11ea-9f02-ac74ff0fef44.png)

**Comment by brrd** [comment]
Yes. It's intended. Codeblocks styling introduced very heavy performance issues (see #274) so I decided to remove it until we code something better. I'll create an issue to keep a track of this.

**Comment by actionless** [comment]
thanks!
