### ISSUE TITLE
Remember window position in Windows

### ISSUE THREAD

**Issue by loopernow** [brrd/abricotine#289]
Most Windows programs remember the size and position of the last program window that was open, so that the next time you open the same program, it opens to the same size and position as last time.

Please implement this for Abricotine.

**Comment by brrd** [comment]
This is supposed to be already the case, thanks to the "electron-window-state" module we use. If you the behavior is different in your case then this is a bug. 

Please try the following steps:

* Open Abricotine
* Menu > Edit > "Open Config Directory"
* Delete the file `window-state.json` 
* Resize Abricotine window and close it
* Reopen Abricotine and tell us what happened

If this doesn't solve your issue, then please post the file `window-state.json` in this thread.

**Comment by loopernow** [comment]
Deleting window-state.json solved the issue. Thanks!
