### ISSUE TITLE
Allow font change

### ISSUE THREAD

**Issue by loopernow** [brrd/abricotine#290]
Please allow users to change the default/displayed font for text in the text window.

**Comment by brrd** [comment]
You already can do this by modifying the theme as described here: https://github.com/brrd/abricotine/blob/master/docs/themes.md

**Comment by tilleul** [comment]
I followed the instructions in https://github.com/brrd/abricotine/blob/master/docs/themes.md and I edited the file theme.less for the default profile, adding "Times New Roman" as the first font everywhere fonts are mentioned but reloading the theme and even reloading the app do not seem to have any effect ... what could I be doing wrong ?

**Comment by brrd** [comment]
@tilleul can you please open a new issue?
