### ISSUE TITLE
windows release problem

### ISSUE THREAD

**Issue by njamescouk** [brrd/abricotine#292]
am getting abricotine-setup-win32-x64.exe is not a valid win32 application for Abricotine 1.0.0

**Comment by brrd** [comment]
Is your OS 32 or 64 bits? 
Abricotine installer is only available for 64 bits windows. If you are running a 32 bits OS you need to build the app from its source.

**Comment by njamescouk** [comment]
no it's 64 bit. weird but must be just me.

**Comment by brrd** [comment]
I can't reproduce this issue on my Win 10 64 bits so I don't know how to help you. I will leave this thread open in case someone else encounters the same issue.

**Comment by njamescouk** [comment]
fair enough

**Comment by brrd** [comment]
Version 1.1 probably fixed this.
