### ISSUE TITLE
2-in-1 feature request: background highlighting, for code and long lines

### ISSUE THREAD

**Issue by egasimus** [brrd/Abricotine#3]
Great job on Abricotine! Just took it for a spin and I'm very impressed :-)

You know how some people prefer to write their Markdown in 80-character lines? How about adding a feature to highlight characters that make a line longer than an user-set limit?

Also, what about giving backticked code a grayish background so it's easier to tell apart from regular text?

**Comment by brrd** [comment]
Good ideas, thanks!
I'm planning to add a way to customize the editor styles in some future release, then it would be possible to customize the code appearance.

**Comment by brrd** [comment]
> Also, what about giving backticked code a grayish background so it's easier to tell apart from regular text?

Done in 0.6.0.

I will create a separate issue for the other feature.
