### ISSUE TITLE
Open markdown files with shift+click

### ISSUE THREAD

**Issue by Mike-HubGit** [brrd/abricotine#303]
Dear authors,

 wonderful peace of software ! What misses to me may be the possibility to make url active to click, for websites as well for other md files. What do you think about it ?

  Thanks a lot,
     Mike

**Comment by brrd** [comment]
This is already the case with URL. You have to press the shift key while hovering the link.

Opening markdown file this way is not supported at this time. I'm editing the title of this issue to keep track of this specific feature request.

Related: #277.
