### ISSUE TITLE
See preview of our page

### ISSUE THREAD

**Issue by mcoulont** [brrd/abricotine#304]
Hello

I don't manage to see a preview of my markdown page. It's written that I can but I don't find.

Could you help please ?

Thanks for your work

**Comment by brrd** [comment]
You can use the menu `View `> `View Document in Browser`. Or just press F6.

**Comment by mcoulont** [comment]
OK so it's necessarily in a browser?

**Comment by brrd** [comment]
What else would you expect?

**Comment by mcoulont** [comment]
2 parallel screens, one for the markdown and one for the preview.

**Comment by brrd** [comment]
The purpose of Abricotine is precisely to avoid this kind of dual pane presentation, cf. README:

> In Abricotine, you can preview your document directly in the text editor rather than in a side pane.

There are plenty of alternatives featuring a preview pane. This won't happen in Abricotine.
