### ISSUE TITLE
32 bit windows package is broken (v. 0.2.2)

### ISSUE THREAD

**Issue by brrd** [brrd/Abricotine#31]
Linux users reported issues with the linux 32 bit package (see #6). Now I wonder if everything is working properly with the 32 bit windows prebuilt binary : `Abricotine-win32-ia32.zip` in [version 0.2.2](https://github.com/brrd/Abricotine/releases/tag/0.2.2). 

If you use (or tried to use) it then your feedback would be really appreciated here.
Thank you.

**Comment by abirwas** [comment]
It's not even starting for me.
![error](https://cloud.githubusercontent.com/assets/10178348/13399473/83fb5270-df29-11e5-8723-4a9568bd5ed8.PNG)

**Comment by brrd** [comment]
Thanks @abirwas. That's exactly what I suspected.
The issue is the same than in #6, so I need to set up an appropriate environment to build this package...

I'm removing this broken package from releases. Windows 32 bit users will have to build the app from source until we get a new working prebuilt binary for this environment.

**Comment by brrd** [comment]
Unfortunately I couldn't find an easy way to provide a 32 bit package for Windows, so as we already do with OSX binary I will rely on other users for building this one.
