### ISSUE TITLE
WYSIWYG

### ISSUE THREAD

**Issue by DoctorSubtilis** [brrd/abricotine#315]
Today I saw [Logseq](https://logseq.com/), with a really interesting markdown editor: by default you see the graphical result of code, but by clicking on a text block you see the code itself.  
This seems to me the best: why not implement it in abricotine as well, with priority before other minor enhancements?  
Thank you!

**Comment by brrd** [comment]
Not sure this suits to Abricotine philosophy, but let's keep this issue for the record. Anyway, you should use Logseq if it answers better to your needs.

**Comment by DoctorSubtilis** [comment]
I think that it suits the "Abricotine philosophy": only one panel.  
Logseq has only this good feature, but has too many problems (it cannot neither open nor save a md file, for example).
