### ISSUE TITLE
Editing default theme to change font does not seem to work

### ISSUE THREAD

**Issue by tilleul** [brrd/abricotine#321]
I'm trying to change the default font of the editor.
I followed the instructions in https://github.com/brrd/abricotine/blob/master/docs/themes.md and I edited the file theme.less for the default profile, adding "Times New Roman" (for example) as the first font on every line where fonts are mentioned ("font-family" etc) but reloading the theme and even reloading the app do not seem to have any effect ... what could I be doing wrong ?

**Comment by brrd** [comment]
Thanks for the issue.

Can you please give the full path of the theme.less you are editing?

**Comment by tilleul** [comment]
I'm editing the file in C:\Users\***\AppData\Local\Programs\abricotine\resources\default\themes\default\theme.less
Could it be an issue because I installed it for a specific user and not for all users ?

**Comment by brrd** [comment]
You are editing the wrong file. The user configuration is stored in User\AppData\Roaming\Abricotine\app on Windows. 

Regardless of your OS you can access it with menu Edit > Open Config Directory.
