### ISSUE TITLE
Add support for GitLab fold tags "<summary>"

### ISSUE THREAD

**Issue by PpChailley** [brrd/abricotine#322]
Gitlab markdown supports a syntax for foldable sections with the code below.

Could you add support for this?

```
<details><summary>Section title</summary>
hidden text
</details>
```

References:
* https://docs.gitlab.com/ee/user/markdown.html#collapsible-section
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary

**Comment by brrd** [comment]
I'm merging this request in #281.
