### ISSUE TITLE
word intelligence boxed by default

### ISSUE THREAD

**Issue by wi-wi** [brrd/abricotine#329]
Hi when I write the word intelligence in the editor a box appears around it, spontaneously. I did not add any code. Funny. Is there a way to stop the box? See screenshot.

![image](https://user-images.githubusercontent.com/53225089/203933157-765e1287-710c-47e1-987b-415622baa8de.png)

**Comment by brrd** [comment]
You obviously searched (Ctrl+F) for the word "intelligence".
