### ISSUE TITLE
Overriding system shortcuts

### ISSUE THREAD

**Issue by bhargavrpatel** [brrd/Abricotine#33]
Please, never override system shortcuts... 
Format > Quote (Command + Q)
Quit app > (Command + Q)

I am not able to close this app unless I use the doc currently.

**Comment by brrd** [comment]
This problem as been reported in #11 and solved with #25.
If you don't want to wait for the next release you can try to build Abricotine from the develop branch where this issue is fixed.
Please check existing issues before posting a new one.
