### ISSUE TITLE
Cannot change theme font

### ISSUE THREAD

**Issue by loopernow** [brrd/abricotine#333]
I've edited the font-family line in [theme-name].less in the Themes directory and reloaded Abricotine, but the editor font does not change.

If I open developer tools and select some text in the file, I can edit the font family in Developer Tools and change the font that way--it points to a file "default.css" in a temp directory. But I don't know if this file is permanent.

The file "default.css" does not reflect the changes I make to [theme-name].less.

Edit: Windows 10, Abricotine v. 1.1.4.

**Comment by brrd** [comment]
Please always give information about your OS and your app version.

Please try View > Development > Reload Theme.

If this still doesn't work, reset configuration: https://github.com/brrd/abricotine/blob/master/docs/configuration.md#reset-configuration
2)

**Comment by loopernow** [comment]
Sorry about that.
