### ISSUE TITLE
fails to select Abricotine for opening file

### ISSUE THREAD

**Issue by Dibal** [brrd/abricotine#336]
Linux file mangers offer selection menu which program should open files with ".md" extension. Abricotine starts as expected -- but without opening the selected file.

Another observation: drag and drop paste entry at last cursor position but not where content was dropped.

**Comment by brrd** [comment]
Duplicate: #327.

**Comment by Dibal** [comment]
#327 is a solution if I open via desktop file, but not via context menu of a file manager.

**Comment by brrd** [comment]
Knowing how most Linux DE work, I believe this is the same issue. You file manager probably uses the declared .desktop file to populate its context menu.

If you think I'm wrong then please provide more information. What is your distro? What is your DE? Did you try editing Abricotine .desktop file as proposed in #327?

**Comment by Dibal** [comment]
You are right, works like a charm.
