### ISSUE TITLE
Android build? Ubuntu Touch? :-)

### ISSUE THREAD

**Issue by DuncanCragg** [brrd/abricotine#340]
This is exactly what I need, on my Ubuntu laptop.

How easy would it be to make an Android build of this?

Or, perhaps more easy for starters, an arm64 Ubuntu Touch build?

I can look into doing this myself if it's reasonably straightforward...

**Comment by brrd** [comment]
We use Electron which builds to desktop only, so I guess this would require to rewrite the whole code base from scratch. I definitely don't want to do this. I'm sorry, you will have to find an alternative.
