### ISSUE TITLE
heading and code autopreview

### ISSUE THREAD

**Issue by protontrigg3r** [brrd/abricotine#341]
It would be nice to have _**autopreview**_ for _**heading**_ and _**code**_ as well. I tried adding them in _**config.json**_ but they seem to be unsupported (i.e.: the preview is displayed but retains the formatting characters **#** and **'''** which instead would be nice if they were hidden, as happens for example with Obsidian).

Is there a particular reason? Is it possible to implement these previews?

**Comment by brrd** [comment]
Duplicate #158
