### ISSUE TITLE
feature: resize image in markdown

### ISSUE THREAD

**Issue by creatxrgithub** [brrd/abricotine#345]
to limit image size in markdown document, eg:

`![image134|10x10,1%](example.svg)`
`![image134](example.svg){width:10px, height:10px}`

**Comment by brrd** [comment]
Abricotine only supports [GFM (GitHub Flavored Markdown)](https://github.github.com/gfm/#images) which unfortunately does not include any size attributes for images. You can use the `<img>` tag as an alternative.

**Comment by creatxrgithub** [comment]
I've tried. 

e.g.

`![](example.svg)`

It works in Abricotine.

https://github.github.com/gfm/#example-484

`<img src="example.svg" style="height: 10px; width:10px;"/>`
`*<img src="example.svg" style="height: 10px; width:10px;"/>`

It works in Github, but not in Abricotine.  It shows the code text.

**Comment by brrd** [comment]
What you are asking for is this feature: #281
