### ISSUE TITLE
"Show menubar" option is useless on OSX

### ISSUE THREAD

**Issue by albertomori** [brrd/Abricotine#35]
In OSX the menu bar is not visibile when press on show menu bar.

**Comment by albertomori** [comment]
Ok, it's the OSX UI, but it isn't clear.

**Comment by brrd** [comment]
I don't understand the problem. Can you provide more details please (screenshots would be useful) ?

**Comment by albertomori** [comment]
It's not a real problem or bug. In OSX the menu bar is outside the window, so the menu item "Show menu bar" doesn't works. Also I think that the menu bar lacks of the File section, isn't it?

![shot_2](https://cloud.githubusercontent.com/assets/262632/13631896/516dcc06-e5e7-11e5-86cf-06990bd3f55d.jpg)
![shot_1](https://cloud.githubusercontent.com/assets/262632/13631898/5194f362-e5e7-11e5-943b-39aa4a29efc6.jpg)

**Comment by brrd** [comment]
OK, so this option must be removed in the OSX version.

> Also I think that the menu bar lacks of the File section, isn't it?

This is probably another OSX weird behaviour because [the File menu does exist](https://github.com/brrd/Abricotine/blob/master/app/menu-window.json#L3). What's in the Abricotine menu?

**Comment by albertomori** [comment]
It seems like a file menu.
![shot_3](https://cloud.githubusercontent.com/assets/262632/13634958/2ebac0e4-e5f9-11e5-931d-efd4189d712a.jpg)

**Comment by brrd** [comment]
> It seems like a file menu.

Yes, this is the File menu. So it is definitely the OSX behaviour.
