### ISSUE TITLE
Menu and shortcut issues (OS X)

### ISSUE THREAD

**Issue by nloveladyallen** [brrd/Abricotine#38]
Functions like New, Open, Save, etc. that by convention are in the File menu are in the Abricotine menu on OS X.

Functions like About, Preferences, Quit, etc. that by convention are in the application menu are completely scattered: About is in the Help menu (like Windows), Preferences are in the Edit menu, and Quit apparently does not exist. 

Preferences is normally tied to ⌘, instead of strikethrough. Quit (which doesn't exist in Abricotine) is normally tied to ⌘Q instead of Close Window. Close Window and Close Document, tied to ⌘Q and ⌘W respectively, appear to be completely identical. (See #32 for more about Close Window/Quit.)

Functions currently use mostly sentence case instead of title case, as is convention on OS X and Windows.

**Comment by brrd** [comment]
We definitely need to create a separate menu for OSX.

> Functions currently use mostly sentence case instead of title case, as is convention on OS X and Windows. 

I didn't know (sentence case is the convention in my native language). I will fix this.

**Comment by brrd** [comment]
I worked on some improvements related to this issue on the [develop branch](https://github.com/brrd/Abricotine/tree/develop). I don't own a mac so I could not try it. If someone could give my some feedback this would be very helpful.

> Functions like New, Open, Save, etc. that by convention are in the File menu are in the Abricotine menu on OS X.
> Functions like About, Preferences, Quit, etc. that by convention are in the application menu are completely scattered
> Preferences is normally tied to ⌘, instead of strikethrough.
> Functions currently use mostly sentence case instead of title case, as is convention on OS X and Windows. 

=> Those should be fixed now.

> Quit apparently does not exist

=> See dedicated issue: #50

> Close Window and Close Document, tied to ⌘Q and ⌘W respectively, appear to be completely identical

Actually they are not: "Close Document" is supposed to clear the content and keep the window open.

I also added the "window" menu on OSX and used the `"role": "help"` attribute on help menu (see https://github.com/atom/electron/blob/master/docs/api/menu-item.md)

Does this fix this issue?

**Comment by nloveladyallen** [comment]
> Functions like New, Open, Save, etc. that by convention are in the File menu are in the Abricotine menu on OS X.
Functions like About, Preferences, Quit, etc. that by convention are in the application menu are completely scattered
Preferences is normally tied to ⌘, instead of strikethrough.

This issue is now fixed in the develop branch.

> Functions currently use mostly sentence case instead of title case, as is convention on OS X and Windows. 

Mostly fixed in the develop branch. Looking through the menus I only notice File>Export as HTML>Default template still in sentence case.

> "Close Document" is supposed to clear the content and keep the window open.

Ah, OK. I didn't notice that I guess. I don't know of any apps that bind ⌘W to clearing the current window. Once #32 is fixed, I might suggest reconsidering this.

> I also added the "window" menu on OSX and used the `"role": "help"` attribute on help menu (see https://github.com/atom/electron/blob/master/docs/api/menu-item.md)

I don't see the Window menu, just Abricotine, File, Edit, Format, Insert, Table, View, and Help. Right now looking at [menu-window.json](https://github.com/brrd/Abricotine/blob/2269844c59d9d21bb0f445279b23b899624b0b84/app/menu-window.json) there doesn't appear to be any items under it, which may be why it isn't displaying (I'm not that familiar with Electron, but this seems like reasonable behavior).

**Comment by brrd** [comment]
@nloveladyallen Thanks for your feedback!

> Mostly fixed in the develop branch. Looking through the menus I only notice File>Export as HTML>Default template still in sentence case.

It's because you kept the old default template in your config. You need to [reset your config](https://github.com/brrd/Abricotine/blob/master/docs/configuration.md#reset-configuration) to see this change.

> I don't know of any apps that bind ⌘W to clearing the current window. Once #32 is fixed, I might suggest reconsidering this.

Most of the time (at least on Linux and Windows) Ctrl+W closes the current view/document/tab/window. Actually, at the very beginning my idea was to design things as if Abricotine supported tabs, in order to facilitate tab feature development that would happen later. This is why Ctrl+W is closing the doc (kind of closing the current tab). But I admit this isn't really clear and we can reconsider it now.

> I don't see the Window menu, just Abricotine, File, Edit, Format, Insert, Table, View, and Help. Right now looking at menu-window.json there doesn't appear to be any items under it, which may be why it isn't displaying (I'm not that familiar with Electron, but this seems like reasonable behavior). 

Ok... I bet this was supposed to be populated automatically with some OSX specific stuff, but obviously this is not the case. Is there any convention about a "Window" menu in OSX?

**Comment by nloveladyallen** [comment]
> It's because you kept the old default template in your config. You need to reset your config to see this change.

OK, yes, that fixed it. Maybe auto-rename "Default template" to "Default Template" for users with pre-existing configs upgrading? 

> Ok... I bet this was supposed to be populated automatically with some OSX specific stuff, but obviously this is not the case. Is there any convention about a "Window" menu in OSX?

As with anything, it differs slightly from app to app (even Apple's own apps), but here's the general convention (taken from Finder)

* Minimize (tied to ⌘M)
* Zoom (not to be confused with Zoom In/Zoom Out, which are in the View menu)
* Cycle Through Windows (tied to ⌘`) (this is not always shown in the menu, but works anyway in any app, including Abricotine)
* Tab-related operations (not relevant to Abricotine, at least not yet)
* Bring All to Front
* The title of every open window, with a check next to the currently active one

Comparing the [Atom menu file](https://github.com/atom/atom/blob/master/menus/darwin.cson) and the menus in Atom, it seems the the last one is auto-populated, but the others must be put in the file.

**Comment by brrd** [comment]
> Maybe auto-rename "Default template" to "Default Template" for users with pre-existing configs upgrading? 

Done: 4f719b9cfe8f0c9759c2d66d675411340ba31b56

I think I'm going to give up the Window menu because I don't know OSX enough to develop it. But if someone want to work on it, he/she will be welcome.

I'm closing this issue since most fixes are done on the develop branch. @nloveladyallen thanks for your help again.
