### ISSUE TITLE
Windows package broken

### ISSUE THREAD

**Issue by Shuunen** [brrd/Abricotine#39]
Hi,

Here is the popup error i got when launching Abricotine 0.3.0 :

![image](https://cloud.githubusercontent.com/assets/439158/13722387/2e686a54-e844-11e5-913e-78ec04ecf152.png)

**Comment by brrd** [comment]
Build errors again and again! :sob: 
I must rebuild and package the whole dependencies on Windows. I need to find an appropriate computer for doing this. Probably next week.

I'm gona remove the package. Right now, you can build the app from source or use the previous version. Sorry for this.

**Comment by Shuunen** [comment]
don't be sorry :) your app is really great, it's my favorite to edit md files

**Comment by brrd** [comment]
Fixed with the new released package: https://github.com/brrd/Abricotine/releases/tag/0.3.0

**Comment by Shuunen** [comment]
Yes working great :) thx
