### ISSUE TITLE
Small issue on TODO list and return

### ISSUE THREAD

**Issue by Shuunen** [brrd/Abricotine#43]
Hi,

Here an example of the behaviour of Abricotine when hitting "Enter" at the end of a TODO line, it does not create another todo on the new line.

![gif](https://cloud.githubusercontent.com/assets/439158/13946321/2693b11c-f014-11e5-8387-8dcfc9cdd60c.gif)

Then as a second issue, when selecting multiple lines and toggling TODO style, it mess up with the star character.

**Comment by brrd** [comment]
1st issue: we need a custom rewrite of CodeMirror's [`continuelist.js` plugin](https://github.com/codemirror/CodeMirror/blob/master/addon/edit/continuelist.js) that would support todolists.

2nd issue is probably a bug somewhere in Abricotine's [`cm-extend-markdown.js`](https://github.com/brrd/Abricotine/blob/master/app/renderer/cm-extend-markdown.js)

**Comment by brrd** [comment]
From @jacobmischka (#161) 

> Interestingly, this works out of the box if you use `-` for bullets intead of `*`.

![peek 2017-03-15 23-19](https://cloud.githubusercontent.com/assets/3939997/23981617/e0fee1da-09d5-11e7-982e-d874e9237f13.gif)

I didn't notice this. It's actually already supported in CodeMirror: https://github.com/codemirror/CodeMirror/blob/master/addon/edit/continuelist.js#L14-L15

Actually the `* [ ]` syntax is not clearly mantionned in [Github flavored markdown](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) even if Github supports it. I think we should use the recommended `- [ ]` syntax in Abricotine. And by the way I'll PR the support for `* [ ]` in CodeMirror.

**Comment by jacobmischka** [comment]
I believe [CodeMirror actually does support it](https://github.com/codemirror/CodeMirror/blob/223a43cd60968fe468835b61166a196c70607020/addon/edit/continuelist.js#L14-L15), unless I'm terrible at reading regexes. Both `listRE` and `emptyListRE` seem to include the boxes. I couldn't figure out why the * didn't work, though.

**Comment by brrd** [comment]
@jacobmischka This may answer you question: https://github.com/codemirror/CodeMirror/pull/4644/commits/9c9a4cb24790772cd75f2de2d5f69c4f020b77bd :wink:

**Comment by jacobmischka** [comment]
Ha yeah, the coincidental `*|-` confused me. I just woke up let's blame that :sleepy:
