### ISSUE TITLE
Abricotine is broken after a configuration update (startup dialog)

### ISSUE THREAD

**Issue by Hitaro** [brrd/Abricotine#45]
- I have installed it by https://aur.archlinux.org/packages/abricotine
- I also tried the Abricotine-linux-x64 package, downloaded from release page.

In both cases, If I run it via a terminal, I get this warning:

For the one installed via AUR:

          (electron) ipc module is deprecated. Use ipcMain module instead.
          { [Error: ENOENT: no such file or directory, open '/home/$USER/.config/chromium/Abricotine/app/schema.json']
          errno: -2,
          code: 'ENOENT',
          syscall: 'open',
          path: '/home/$USER/.config/chromium/Abricotine/app/schema.json' }
          (electron) loadUrl is deprecated. Use loadURL instead.

For the [pre-made linux package](https://github.com/brrd/Abricotine/releases) that I have downloaded:

    $Abricotine-linux-x64$ ./Abricotine 
        (electron) ipc module is deprecated. Use ipcMain module instead.
        (electron) loadUrl is deprecated. Use loadURL instead.

`cat /home/$USER/.config/chromium/Abricotine/app/schema.json`: { "schema": 1 }

Here is what I got when I run it for the first time:

![err](https://cloud.githubusercontent.com/assets/18015032/13987356/d5cfeb8a-f124-11e5-80b2-54e88977a873.png)

I chose _YES_ And nothing happened: https://ptpb.pw/9hNk --> Ctrl+C

Next time I clicked on _NO_ and it came up with the warning that I put it above.

     My OS: Archlinux 64 bit
     My Desktop: Plasma v5.5

**Comment by Hitaro** [comment]
- `npm install`: https://ptpb.pw/xT_G

- 1st `npm start`: https://ptpb.pw/3jIJ  --> I still get that warning:

- 2nd `npm start`:  https://ptpb.pw/Nkdg

- `cat ~/npm-debug.log`:https://ptpb.pw/gam7

**Comment by brrd** [comment]
Thanks for your last post which is clear.

I am pretty sure that this as nothing to do with the "XXX is deprecated" messages.

It looks like the 2nd `npm start` was run from outside the Abricotine directory, is it?
Can you try to browse to `/home/$USER/.config/Abricotine/` and tell me why what you see inside?

**Comment by Hitaro** [comment]
> It looks like the 2nd npm start was run from outside the Abricotine directory

Woops, right

---
- `rm -rf ~/.config/chromium`
- `npm start`: 

        > Abricotine@0.3.0 start /home/$USER/Downloads/Abricotine-0.3.0
        > electron.
        (electron) ipc module is deprecated. Use require("electron").ipcMain instead.
    Then It shows a No/Yes dialogue that has been showed in the first post of this issue.
    I chose `No`. Then it showed another prompt:

![err](https://cloud.githubusercontent.com/assets/18015032/14013370/c74fce68-f1c9-11e5-9b3f-1735d97758ac.png)

Uncaught Exception: https://ptpb.pw/AN8c --> Then: nothing! It does not open the app!

* If I chose Yes, the app cames up with this warning on terminal screen: 

        > Abricotine@0.3.0 start /home/$USER/Downloads/Abricotine-0.3.0
        > electron .
        (electron) ipc module is deprecated. Use require("electron").ipcMain instead.
        { [Error: ENOENT: no such file or directory, open '/home/$USER/.config/Abricotine/app/schema.json']
          errno: -2,
          code: 'ENOENT',
          syscall: 'open',
          path: '/home/$USER/.config/Abricotine/app/schema.json' }
        (electron) loadUrl is deprecated. Use loadURL instead.

**Comment by Hitaro** [comment]
`cd cd /home/$USER/.config/Abricotine` ---> Contents: https://ptpb.pw/QMkw

**Comment by brrd** [comment]
@Hitaro Many thanks for your reports which are really useful. I could reproduce the issue on my ubuntu 64 bits so this is not specific to archlinux.

As far as I can see, several issues are involved here. It needs further investigation to fix them all...

Right now, running `./Abricotine --reset` (with released package) or `npm start -- --reset` (with custom build) should fix the issue once and for all.

**Comment by hermes3por3** [comment]
I found that changing the permissions for **Group Access** to **Read and write** instead of **Read-only** for the executable file (after extracting the ZIP file, the permissions were just Read-only) lets me run the program without the javascript exception. The config folder appears in `/home/$USER/.config/chromium/Abricotine/` I am running Ubuntu 15.10 x64.
