### ISSUE TITLE
Bad config path

### ISSUE THREAD

**Issue by brrd** [brrd/Abricotine#46]
Abricotine configuration files should be stored in `/home/$USER/.config/Abricotine` instead of `/home/$USER/.config/chromium/Abricotine`.

Related to https://github.com/atom/electron/issues/3709. We need to update electron.

This is maybe involved in issue #45.

**Comment by nloveladyallen** [comment]
Now that Electron is updated, can this be closed?

**Comment by brrd** [comment]
> Now that Electron is updated, can this be closed?

Yes!
