### ISSUE TITLE
Only first latex equation rendered in line

### ISSUE THREAD

**Issue by benjaminirving** [brrd/Abricotine#47]
Hi, 

Firstly, thanks for the great tool. It seems that there is a small bug where only the first latex equation in each line is rendered. 

e.g.
`$$ x^2 $$ and $$ x^3 $$`

results in just the x^2 being rendered. Unless there is a bug with my setup. 

p.s. had a look in cm-extend-autopreview.js but my javascript abilities are non-existent

**Comment by elfnor** [comment]
Also previewing latex equations on multiple lines doesn't render:

```
$$  
x^2  
x^3  
$$
```

Otherwise great tool, Thanks

**Comment by brrd** [comment]
@elfnor Multiline preview is related to another issue: #51

**Comment by brrd** [comment]
Related to https://github.com/codemirror/CodeMirror/issues/3998
