### ISSUE TITLE
relative image paths do not get updated on export

### ISSUE THREAD

**Issue by brunnre8** [brrd/Abricotine#49]
When using the `Insert-->Image-->Copy all images in a local folder` function it copies all the pictures into `./$FILENAME_files/$PICTURE`

However it does so relative, meaning that if one exports the html via `Export as HTML` to a location other than the storage directory of the markdown file the images aren't found and therefore appear as a broken link.

I see 2 options that should fix the issue:
- Set the path to an absolute one
- copy the files over to the new location.

**Comment by brrd** [comment]
> I see 2 options that should fix the issue

A third option would be to encode images as base 64. 

> Set the path to an absolute one

Yes, but it's not really "portable".

I think the best solution is to copy relative images to some `target.html_files/images` directory. Actually, this is [what was mainly planned](https://github.com/brrd/Abricotine/blob/master/app/renderer/export-html.js#L40) (until I forgot about it :sweat_smile:).

**Comment by brunnre8** [comment]
>A third option would be to encode images as base 64.
Binary blobs seem just a bit hacky to me :wink: 

Thank you very much for taking care of it, awesome program by the way.
