### ISSUE TITLE
icon on linux package

### ISSUE THREAD

**Issue by robsonsobral** [brrd/Abricotine#52]
Hi! I downloaded the package for Linux, but it doesn't include the icon. Is it possible to add it, please?

Thank you

**Comment by brrd** [comment]
What are you exactly asking for? 
Do you want Abricotine icon to appear on your taskbar and in your installed programs? -> see #8
Or you are just looking for [Abricotine icon](https://github.com/brrd/Abricotine/tree/master/icons)?

**Comment by robsonsobral** [comment]
I want to put the icon on a `.desktop` file. Just this.
