### ISSUE TITLE
Support translations

### ISSUE THREAD

**Issue by psimacek** [brrd/Abricotine#59]
Hi, 

please, how to translate this superb app?

Thanks **Thomas** and others for your work!

P.

**Comment by brrd** [comment]
Hi! Right now there is no support for internationalization, but I think this would be a good feature to add.

**Comment by psimacek** [comment]
Thanks Thomas, I 'm looking forward to it!

**Comment by Shuunen** [comment]
I can help translate it to French :)

**Comment by cicithesquirrel** [comment]
Maybe I can help on this one. What do you thing of using NPM [i18n](https://www.npmjs.com/package/i18n)?

**Comment by cicithesquirrel** [comment]
Well, I should have read i19n's documentation before writing :
> During configuration, i18n reads all known locales into memory and prepares to keep that superfast object in sync with your files in filesystem as configured

So, not sure this is the right candidate...
