### ISSUE TITLE
Consider Fira Code for the default font

### ISSUE THREAD

**Issue by adiultra** [brrd/Abricotine#61]
[Fira Code](https://github.com/tonsky/FiraCode) is an amazing font which looks good is easy on eyes and includes special symbols that would act functionality to arbicotine such as Arrows etc.

![Fira code](https://github.com/tonsky/FiraCode/raw/master/showcases/all_ligatures.png)

Also the heading fonts don't need to be that **BOLD**.

**Comment by brrd** [comment]
I didn't know this font. This is an interesting suggestion.

> Also the heading fonts don't need to be that BOLD.

You will be able to set it as you wish once #9 is implemented.
