### ISSUE TITLE
Support for Windows,  Mac OS Line Endings

### ISSUE THREAD

**Issue by psimacek** [brrd/Abricotine#62]
When I save document in Linux and share it with Windows computer, my text is in only one block. Without paragraphs etc.

The problem is in line endings.

**Comment by darahak** [comment]
@psimacek Is this still an issue on `0.4.0`? I opened a file with LF line endings and the display was correct.

**Comment by psimacek** [comment]
This issue persists. When I save text in linux Abricotine 0.4.0. (.md, .txt), in Windows is it in one block. If I save it in Gedit with line endings Windows, no problem in Wordpad or so...

**Comment by darahak** [comment]
Wait, you're mentioning Wordpad now, so I'm confused...

> When I save text in linux Abricotine 0.4.0. (.md, .txt), in Windows is it in one block.

Which editor are you using here?
Is the issue about how Abricotine writes, or how it reads these files?

**Comment by psimacek** [comment]
Hi, normally I'm working in linux with Abricotine. But sometimes I must save some text for using in Windows. There is Notepad (sorry, not Wordpad). And when I open document from Abricotine (linux) in Notepad (Windows) text is in one block, without paraphs, spaces etc. Then I have to use Gedit which has in save dialog option: Line endings, or adjustment line. If I choose Windows, not Linux/Unix or Mac OS Classic, document is same as in Abricotine. Except markdown features. Only plain text, but that's enough for me.

**Comment by darahak** [comment]
Thanks for clarifying!

So what you really need is the same option in Abricotine to let you choose the type of line endings.

In the mean time, you should probably use a better editor like [Notepad++](https://notepad-plus-plus.org/) (it also has an option to convert line endings).
If you're used to gedit, they also have [Windows installers](http://ftp.gnome.org/pub/GNOME/binaries/win64/gedit/).

**Comment by psimacek** [comment]
Thanks a lot. I'll try it. But I hope, that Abricotine will get this option.

**Comment by brrd** [comment]
I can't reproduce this issue. Markdown files created with Abricotine on Linux are formatted as expected (including line breaks) when reading them with notepad on Windows.

If your issue still occurs then please provide additional information to help us reproducing it.
