### ISSUE TITLE
integration Pandoc

### ISSUE THREAD

**Issue by framatophe** [brrd/Abricotine#65]
Pandoc is a wonderful converter. With Pandoc, it is possible to use mardown documents and convert them in PDF with a LaTeX template (of an HTML template when converting in HTML). 

For that, Pandoc use its "own" markdown. For example, it is possible to integrate some bibliographic elements : ``bla bla bla [@dupont1956] blabla``

Here [is an explanation page](http://pandoc.org/README.html#pandocs-markdown) on pandoc's markdown. I think that is would not be very interesting for a complete integration of pandoc's markdown in abricotine, but some of of them are very useful : 

   - definition lists
   - grid- and multilines tables
   - superscripts and subscripts
   - citation (only coloring references like ``[@dupont1956]``)

Here is [a document](https://blog.statium.link/fr/home/un-apercu-de-pandoc) for a short overview of Pandoc.

**Comment by brrd** [comment]
Duplicate: #14
