### ISSUE TITLE
OS X package for latest stable

### ISSUE THREAD

**Issue by nloveladyallen** [brrd/Abricotine#66]
There's no OS X package. Here's one I built if you need it: https://www.dropbox.com/s/bx2bjrqbde1pbx5/Abricotine-darwin-x64.zip?dl=0

Not codesigned, but that's normal for open-source projects.

**Comment by brrd** [comment]
I added it in releases: https://github.com/brrd/Abricotine/releases/tag/0.3.2
Thanks

**Comment by nloveladyallen** [comment]
Here's 0.3.3: https://www.dropbox.com/s/a353acb9kpdvnoi/Abricotine-darwin-x64.zip?dl=0

(What's the best way to contact you for future releases?)

**Comment by brrd** [comment]
@nloveladyallen :+1: thanks

> What's the best way to contact you for future releases?

Let's simply reopen this thread for submitting binaries.

**Comment by brrd** [comment]
Actually I'll open a new thread in order to make it clearer. Sounds better.

**Comment by brrd** [comment]
See #89
