### ISSUE TITLE
LaTeX Equations Support

### ISSUE THREAD

**Issue by RoyiAvital** [brrd/Abricotine#7]
Hi,

Could you please add support for LaTeX Equations support.
The reference I can give you is [StackEdit](https://github.com/benweet/stackedit).

We really need new MD editor, bravo!

**Comment by brrd** [comment]
Hi,
Abricotine already supports LateX formulas. Formulas must be wrapped with `$$` symbols: `$$\sum_{i=1}^{n} (v_{i-1}+u_{i})$$`
Thanks to MathJax, math formula is previewed into the editor if you check "Math" in the "Auto Preview" menu. It is also rendered when you export the doc to HTML.

**Comment by jdallmann** [comment]
Hi,

Would it be possible to display math when wrapped only in single '$'s too (or is there an easy way to hack to config to allow this)? Doing so would help to make Abricotine more compatible with Pandoc Markdown. Also, it's looking awesome so far!

**Comment by RoyiAvital** [comment]
@brrd , I will try it.
Also, as written above, inline equation using $ <> $ would be amazing.

Thank You.

**Comment by adiultra** [comment]
Hi, I know MathJax is being used now, but I would like to recommend [Katex](https://khan.github.io/KaTeX/).

The basic reason is, it is fast, very much faster than MathJax. It does lack extremly advanced features, But it has many.

There is also a package of [markdown-katex](https://atom.io/packages/atom-markdown-katex) for aton.

**Comment by brrd** [comment]
Hi there,
I just created two issues #15 and #16 from your comments. I'm closing this one.
Thanks

**Comment by RoyiAvital** [comment]
Hi,
Please don't move to Katex.
We want full support in the {align} environment.

Or to the least allow the user to toggle between MathJax and Katex.
Thank You.

**Comment by adiultra** [comment]
I am totally with both :+1:
