### ISSUE TITLE
Code Block Highlighting

### ISSUE THREAD

**Issue by dataBaseError** [brrd/Abricotine#72]
If a code block ending mark (```) is used with white spaces preceding it then in editor syntax highlighting will appear as still within a code block. When the document is viewed in the browser it will show up correctly.

For example (_note_ `\s` is showcasing a space) the the last line in the code block is `\s````

``````
```
code
 ```
``````

All following code will appear as though it is part of the code block.

**Comment by darahak** [comment]
I can't reproduce this issue. Maybe it was fixed by a previous commit?

**Comment by brrd** [comment]
> I can't reproduce this issue.

Me neither. Probably fixed when CodeMirror was updated to 5.15.2 (5e98787d8e26e09ca99d54a38d987e92835c20f1).
