### ISSUE TITLE
Large files not usable

### ISSUE THREAD

**Issue by DanBennettUK** [brrd/Abricotine#76]
I have a file that is 678KB (>94,000 words)...

Takes a while to load and when in use, typing is incredibly slow - can take a long time for text to appear.

**Comment by brrd** [comment]
I did some tests with a 1MB document and found out that latency comes from several methods:

| Method                   | Load doc          | Edit doc | Move cursor |
| ------------------------ | ------------------- | ---------- | --------------- |
| `abrPane.updateToc`  | 13426.697ms   | 1501.992ms | - |
| `abrPane.spyCursor`   | 4.445ms         | 3.172ms | - |
| `abrDoc.autopreview` | 338.541ms       | 158.882ms | 240.584ms   |

`abrPane.updateToc` and `abrPane.spyCursor` should be run in a background thread.

Additionally we can improve a bit performances by modifying `abrDoc.autopreview`:

* When editing must, only process edited lines.
* When moving cursor/selection, only process previously selected lines + currently selected lines.

**Comment by brrd** [comment]
I fixed this on [develop branch](https://github.com/brrd/Abricotine/tree/develop) so this will be working better in the next release.
