### ISSUE TITLE
Preview multiple images on the same line

### ISSUE THREAD

**Issue by jcbrinfo** [brrd/Abricotine#77]
If I put two or more images on the same line, the auto preview only works for the first image on that line. The other ones remain displayed as Markdown code, no matter what I do. Here is an example:

```
![foo](https://img.shields.io/badge/image-ok-green.svg)  ![bar](https://img.shields.io/badge/image-ok-green.svg) ![baz](https://img.shields.io/badge/image-ok-green.svg)
```

This example appears like this on Abricotine (with the auto preview of the images enabled):

> ![foo](https://img.shields.io/badge/image-ok-green.svg)  `![bar](https://img.shields.io/badge/image-ok-green.svg) ![baz](https://img.shields.io/badge/image-ok-green.svg)`

However, I expected the following:

> ![foo](https://img.shields.io/badge/image-ok-green.svg)  ![bar](https://img.shields.io/badge/image-ok-green.svg) ![baz](https://img.shields.io/badge/image-ok-green.svg)

**Comment by brrd** [comment]
This is actually the same issue than #47.

This comes from an bug in CodeMirror which was finally fixed [here](https://github.com/codemirror/CodeMirror/issues/3998). CodeMirror dependency will be updated in a future release.

**Comment by jcbrinfo** [comment]
Thank you.
