### ISSUE TITLE
Shortcut keys not shown in menu

### ISSUE THREAD

**Issue by ShubhamGG** [brrd/Abricotine#79]
I am on Ubuntu 16.04 with Abricotine v0.3.2. There is no mention of the keyboard shortcuts in the software. I looked it up and found this:
![Image of Menu](https://websetnet.r.worldssl.net/wp-content/uploads/2016/02/abricotine-markdown-editor-on-linux-3.jpg)
but no shortcuts are visible to me on my desktop.

Was this removed for some reason? There should be some option to show/edit the key shortcuts.

**Comment by brrd** [comment]
I guess you are using Unity as your desktop manager, is it?

> Was this removed for some reason?

No. I'm using Gnome 3 and everything is fine. I think it is okay on Windows and OSX too.

It is probably an issue with Electron. Abricotine uses a quite old version, I need to update it soon. This will maybe fix your issue.

**Comment by nloveladyallen** [comment]
Electron has now been upgraded. Do you still see the issue?

**Comment by brrd** [comment]
> Electron has now been upgraded.

Just to clarify: it's still on the develop branch, so one needs to build the app from source to try it.

**Comment by brrd** [comment]
I'm closing this thread until we get more information about this issue.
