### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by Paviluf** [brrd/Abricotine#81]
It will be great to have a dark theme like the Markdown Preview from Atom

https://github.com/atom/markdown-preview#markdown-preview-package

![](https://cloud.githubusercontent.com/assets/378023/10013086/24cad23e-6149-11e5-90e6-663009210218.png)

Thanks !

**Comment by brrd** [comment]
Depends on #9.

**Comment by Netherdrake** [comment]
+1

**Comment by svenio** [comment]
+1

**Comment by brrd** [comment]
Added in [Abricotine 0.4.0](https://github.com/brrd/Abricotine/releases/tag/0.4.0).
