### ISSUE TITLE
Can't quit application on MacOSX

### ISSUE THREAD

**Issue by mica100** [brrd/Abricotine#82]
I'm using v0.3.2 on Mac OSX 10.11.4 (El Captain). Application is running fine and editor windows can be closed with CMD+W. It's not possible to quit the application neither with CMD+Q nor menu Abricotine -> Quit.

**Comment by nloveladyallen** [comment]
This is fixed on the develop branch.

**Comment by brrd** [comment]
@nloveladyallen Thanks

**Comment by mica100** [comment]
But it's working via Right-mouse click on dock-bar.

Thanks for the fix.
