### ISSUE TITLE
OS X installation instructions, still accurate?

### ISSUE THREAD

**Issue by derekderaps** [brrd/Abricotine#88]
I see an OS X release on the [releases page](https://github.com/brrd/Abricotine/releases) but the [installation instructions](https://github.com/brrd/Abricotine/blob/master/docs/installation-and-usage.md) say,
> For OS X users, you must have Homebrew and Hombrew Cask installed and run: `$ brew cask install abricotine`.

Is this still accurate, or do the installation instructions need updating? Thanks!

**Comment by nloveladyallen** [comment]
Either can be used.

**Comment by brrd** [comment]
> Either can be used

Yes. But I admit this is not really clear in docs, this needs an update.
