### ISSUE TITLE
Adding a missing binary

### ISSUE THREAD

**Issue by brrd** [brrd/abricotine#89]
Contributors can use this thread to submit a binary. 
Just post the link to the .zip file here and I will drop it to the release page.

**Comment by CxRes** [comment]
You should be able to do this with https://github.com/electron-userland/electron-packager on wine or homebrew.

**Comment by brrd** [comment]
@CxRes It's already working like this. I already use a win 64 bits and linux 32 bits but I don't have enough time to create and manage more environments. This is why I'm asking for user contributions.
