### ISSUE TITLE
Theming Support 

### ISSUE THREAD

**Issue by TomBous** [brrd/Abricotine#9]
First of all, thank you for this amazing app ! I've been searching for this for almost 2 years... I was using StackEdit until now.

I know you've planned theming support, as you mentioned it on another issue, but i thought this "feature request" deserve a proper issue (more visibility for future users). 

Thanks again for your hard and much appreciated work ! :)

**Comment by brrd** [comment]
Added in [Abricotine 0.4.0](https://github.com/brrd/Abricotine/releases/tag/0.4.0).
