### ISSUE TITLE
Please create a Snap package

### ISSUE THREAD

**Issue by Netherdrake** [brrd/Abricotine#90]
I love this App. Its by far the best markdown editor :)

Is it possible to create a `snap` package for it?
https://developer.ubuntu.com/en/snappy/build-apps/your-first-snap/

This way it will become available to massive number of Ubuntu/Fedora/etc. Linux installs.

**Comment by nloveladyallen** [comment]
See: http://www.linuxuk.org/post/20160518_snapping_electron_based_applications_simplenote/

**Comment by brrd** [comment]
I'm sorry but this is not planned. For now we will focus on more classical solutions such as rpm and deb packages. We would consider moving to Snap when it will be more supported/used. 

You can read #78 (about Flatpack, witch is basically the same) if you want more explanations about this decision.

**Comment by Netherdrake** [comment]
@brrd Hopefully it gets more widely adopted soon, so you don't have to go trough the pains of building debs and rpms and stuff.
