### ISSUE TITLE
Inconsistent list indentation in editor

### ISSUE THREAD

**Issue by tmr232** [brrd/Abricotine#93]
When pasting the following MD in Abricotine,

``` markdown
There's an issue with list item indentation.

- This is the top-level list.
 - This is a second level.
  - This is also the second level.
- And the first level again.
```

I see this:

![image](https://cloud.githubusercontent.com/assets/1386239/16731002/95e8baf0-477e-11e6-9e0d-0759432c75ea.png)

This makes it very hard to edit lists in a reliable manner.

**Comment by krbaehrle** [comment]
Not sure if it is the same bug, but I guess so.

As far as I know, 2 whitespaces before a list entry should result in a nested list. But it doesn't. Using nested lists in Abricontine is a bit tricky...

Idea. Would it help if you automatically replace for example two whitespaces with a tab, if they are placed before a list entry?

![grafik](https://cloud.githubusercontent.com/assets/24965001/25860702/ac939db8-34e2-11e7-80ce-c01885a89e21.png)

**Comment by tmr232** [comment]
I agree in that indentation should reflect the rendered markdown result, not the whitespace used.

**Comment by brrd** [comment]
Sure. There is definitely something to improve here...

> Not sure if it is the same bug, but I guess so.

We can keep this in the same issue. We must fix all nested lists anyway.

**Comment by abderrahmane-tj** [comment]
Any news on this ?
