### ISSUE TITLE
[Feature] Detect file changes and auto-reload

### ISSUE THREAD

**Issue by Netherdrake** [brrd/Abricotine#94]
If file is changed from another program (ie. during sync between computers), update it to reflect the latest version. 
Otherwise, user is at risk of saving old version on top of new one.

**Comment by nloveladyallen** [comment]
In order to do this, Abricotine would have to be doing nearly constant disk I/O, as well as storing the initial file in memory even after edits (though it may already do that, I'm not sure). Most programs don't do this and for good reason.

**Comment by jtojnar** [comment]
Operating systems offer mechanisms like [inotify](https://en.wikipedia.org/wiki/Inotify) that will tell the program if the file changed without the need for periodic checking.

**Comment by nloveladyallen** [comment]
@jtojnar Sorry, I should know that. I looked into it and Node actually provides an [API](https://nodejs.org/docs/v6.3.0/api/fs.html#fs_fs_watch_filename_options_listener) that wraps around different OSs' file tracking APIs.

**Comment by Netherdrake** [comment]
Atom does it too, perhaps you could look how they implemented it.

**Comment by darahak** [comment]
What about [chokidar](https://github.com/paulmillr/chokidar)?
It looks pretty good if you need a cross-platform watcher.
It uses polling except on OS X, where it can use the FSEvents API.

Atom uses [pathwatcher](https://github.com/atom/node-pathwatcher).

**Comment by darahak** [comment]
FYI, I'm trying an implementation with chokidar.
I'll make a PR if it's good enough.

**Comment by Netherdrake** [comment]
@darahak Wooohooo, thank you so much. Once Abricotine gets this feature, its ubeatable.
