### ISSUE TITLE
Packager makes broken packages

### ISSUE THREAD

**Issue by nloveladyallen** [brrd/Abricotine#95]
Introduced with PR #85. Build seems to succeed, but opening the package results in the following error:

<img width="532" alt="screen shot 2016-07-12 at 9 10 34 pm" src="https://cloud.githubusercontent.com/assets/10617484/16788701/2320f90e-4875-11e6-8e72-d72db26bb9ef.png">

The packager also says it's packaging with Electron 0.35, instead of 1.2, which is probably the root of the problem.

`npm start` works perfectly.

**Comment by brrd** [comment]
> The packager also says it's packaging with Electron 0.35, instead of 1.2, which is probably the root of the problem.

Yes it is. I'll fix this.
