### ISSUE TITLE
How to help with translations?

### ISSUE THREAD

**Issue by gnacho** [brrd/Abricotine#99]
I recently started to use this program and I think is awesome. I just feel like would be easier to use for other users if had localizations. I would like to help to translate to my own language (Spanish) but I'm not sure where to do. Any tip?

**Comment by brrd** [comment]
Duplicate with #59.

Thanks to @cicithesquirrel huge work we will get localization support in the next release. You can check the develop branch to see how it works. Or you can wait for the documentation which would come with the release (not written yet).
